import Foundation
import Supabase
import Combine
#if os(iOS)
import UIKit
#endif

// MARK: - Auto-printing Statistics
struct AutoPrintStats {
    var totalNewOrdersPrinted: Int = 0
    var totalReadyItemsPrinted: Int = 0
    var lastPrintTime: Date? = nil
    var printFailures: Int = 0
    
    mutating func recordNewOrderPrint() {
        totalNewOrdersPrinted += 1
        lastPrintTime = Date()
    }
    
    mutating func recordReadyItemPrint() {
        totalReadyItemsPrinted += 1
        lastPrintTime = Date()
    }
    
    mutating func recordPrintFailure() {
        printFailures += 1
    }
    
    mutating func reset() {
        totalNewOrdersPrinted = 0
        totalReadyItemsPrinted = 0
        lastPrintTime = nil
        printFailures = 0
    }
}

class OrderManager: ObservableObject {
    static let shared = OrderManager()
    
    private let supabaseManager = SupabaseManager.shared
    private let printerManager = PrinterManager.shared
    private let autoPrintQueue = DispatchQueue(label: "auto-print-queue", qos: .userInitiated)
    
    @Published var orders: [Order] = []
    @Published var allOrders: [Order] = []  // Add missing allOrders property
    @Published var isLoading = false
    @Published var errorMessage: String? = nil
    @Published var isRealtimeConnected = false
    @Published var newOrderIds: Set<String> = []
    
    // Auto-printing tracking
    @Published var autoPrintingEnabled = false
    @Published var lastAutoPrintResult: String? = nil
    @Published var autoPrintingInProgress = false
    @Published var autoPrintStats = AutoPrintStats()
    internal var printedNewOrders: Set<String> = []
    internal var printedReadyItems: Set<String> = []
    internal var printedNewItems: Set<String> = [] // Track individual items

    @Published var currentDraftOrder: Order? = nil // For managing the active draft order
    @Published var localDraftOrders: [String: Order] = [:] // Local draft orders not yet saved to database
    
    private var realtimeChannel: RealtimeChannelV2?
    private var cancellables = Set<AnyCancellable>()

    // Placeholder types for MenuItemSize and Topping, assuming they exist elsewhere
    // If not, these would be String or [String] for IDs
    typealias MenuItemSizeId = String // String ID for MenuItemSize
    typealias ToppingId = String      // String ID for Topping

    // Define status constants
    let ORDER_STATUS_DRAFT = "draft"
    let ORDER_ITEM_STATUS_DRAFT = "new" // Use 'new' status for items in draft orders (per DB constraint)
    let ORDER_STATUS_NEW = "new" // For when order is confirmed to kitchen

    enum OrderManagerError: Error, LocalizedError {
        case notImplemented
        case generalError(String)
        case missingRestaurantId
        case missingUserId
        case itemFetchFailed(String) // menuItemId
        case orderUpdateFailed(String) // orderId
        case orderItemUpdateFailed(String) // orderItemId

        var errorDescription: String? {
            switch self {
            case .notImplemented:
                return "error_not_implemented".localized
            case .generalError(let message):
                return message
            case .missingRestaurantId:
                return "error_missing_restaurant_id".localized
            case .missingUserId:
                return "error_missing_user_id".localized
            case .itemFetchFailed(let menuItemId):
                return String(format: "error_item_fetch_failed".localized, menuItemId)
            case .orderUpdateFailed(let orderId):
                return String(format: "error_order_update_failed".localized, orderId)
            case .orderItemUpdateFailed(let orderItemId):
                return String(format: "error_order_item_update_failed".localized, orderItemId)
            }
        }
    }

    // MARK: - Payload Structs for Supabase
    struct NewOrderPayload: Codable {
        let restaurant_id: String
        let table_id: String
        let session_id: String
        let guest_count: Int?
        var status: String
        var total_amount: Double = 0 // Initial total price
        // order_number can be generated by a database trigger or function
    }

    struct NewOrderItemPayload: Codable {
        let order_id: String
        let menu_item_id: String
        let quantity: Int
        let notes: String?
        let restaurant_id: String
        var price_at_order: Double // Price of the item at the time of order (including size/toppings)
        var status: String
        let menu_item_size_id: MenuItemSizeId?
        let topping_ids: [ToppingId]?
    }

    struct UpdateOrderItemPayload: Codable {
        let quantity: Int
        let notes: String?
        var updated_at: String = ISO8601DateFormatter().string(from: Date())
        // Potentially price_at_order if quantity/options change price
    }
    
    private init() {
        // Monitor authentication state changes
        setupAuthenticationMonitoring()
        loadAutoPrintingSettings()
    }
    
    deinit {
        //realtimeChannel?.unsubscribe()
        cancellables.removeAll()
    }

    // MARK: - New Order Creation & Management

    @MainActor
    public func createLocalDraftOrder(orderId: String, table: Table) async {
        guard let restaurantId = supabaseManager.currentRestaurantId else {
            print("Cannot create local draft order - no restaurant ID")
            return
        }
        
        // Create a unique session ID for this order (following web app pattern)
        let sessionId = UUID().uuidString
        
        // Create a local draft order that doesn't exist in database yet
        let localDraftOrder = Order(
            id: orderId,
            restaurant_id: restaurantId,
            table_id: table.id,
            session_id: sessionId, // Unique session per order
            guest_count: table.capacity,
            status: .draft,
            total_amount: 0.0,
            order_number: nil, // Will be generated when saved to database
            created_at: ISO8601DateFormatter().string(from: Date()),
            updated_at: ISO8601DateFormatter().string(from: Date()),
            table: table,
            order_items: [],
            payment_method: nil,
            discount_amount: nil,
            tax_amount: nil,
            tip_amount: nil
        )
        
        localDraftOrders[orderId] = localDraftOrder
        currentDraftOrder = localDraftOrder
        print("Created local draft order: \(orderId) for table: \(table.name)")
    }

    @MainActor
    private func saveLocalOrderToDatabase(_ localOrder: Order) async throws -> Order {
        guard let restaurantId = supabaseManager.currentRestaurantId else {
            throw OrderManagerError.missingRestaurantId
        }
        guard let userId = supabaseManager.currentUser?.id else {
            throw OrderManagerError.missingUserId
        }

        // First create the order in database (use 'new' since 'draft' is not allowed)
        let newOrderPayload = NewOrderPayload(
            restaurant_id: restaurantId,
            table_id: localOrder.table_id,
            session_id: localOrder.session_id ?? UUID().uuidString, // Use the same session_id from local order
            guest_count: localOrder.guest_count,
            status: "new" // Database only allows: 'new','serving','completed','canceled'
        )

        let createdOrder: Order = try await supabaseManager.client
            .from("orders")
            .insert(newOrderPayload, returning: .representation)
            .select("*, table:tables(*)")
            .single()
            .execute()
            .value

        // Now save all order items
        var savedOrderItems: [OrderItem] = []
        if let items = localOrder.order_items {
            print("💾 Saving \(items.count) order items to database")
            
            // Debug: Print all items before saving
            for (index, item) in items.enumerated() {
                print("🔍 Local item \(index + 1): id=\(item.id), menu_item=\(item.menu_item_id), qty=\(item.quantity), price=\(item.price_at_order)")
            }
            
            for (index, item) in items.enumerated() {
                print("💾 Saving item \(index + 1)/\(items.count): \(item.menu_item?.displayName ?? "Unknown") x\(item.quantity)")
                
                do {
                    let orderItemPayload = NewOrderItemPayload(
                        order_id: createdOrder.id,
                        menu_item_id: item.menu_item_id,
                        quantity: item.quantity,
                        notes: item.notes,
                        restaurant_id: restaurantId,
                        price_at_order: item.price_at_order,
                        status: "new",
                        menu_item_size_id: item.menu_item_size_id,
                        topping_ids: item.topping_ids ?? [] // Ensure non-nil array
                    )

                    let savedItem: OrderItem = try await supabaseManager.client
                        .from("order_items")
                        .insert(orderItemPayload, returning: .representation)
                        .select("*, menu_item:menu_items(*), menu_item_size:menu_item_sizes(*)")
                        .single()
                        .execute()
                        .value

                    savedOrderItems.append(savedItem)
                    print("✅ Successfully saved item \(index + 1): \(savedItem.id)")
                    
                } catch {
                    print("❌ Error saving item \(index + 1): \(error)")
                    
                    // Try without optional fields that might cause issues
                    struct SimplifiedOrderItemPayload: Codable {
                        let order_id: String
                        let menu_item_id: String
                        let quantity: Int
                        let restaurant_id: String
                        let price_at_order: Double
                        let status: String
                    }
                    
                    let simplifiedPayload = SimplifiedOrderItemPayload(
                        order_id: createdOrder.id,
                        menu_item_id: item.menu_item_id,
                        quantity: item.quantity,
                        restaurant_id: restaurantId,
                        price_at_order: item.price_at_order,
                        status: "new"
                    )
                    
                    do {
                        print("🔄 Retrying with simplified payload for item \(index + 1)")
                        let savedItem: OrderItem = try await supabaseManager.client
                            .from("order_items")
                            .insert(simplifiedPayload, returning: .representation)
                            .select("*, menu_item:menu_items(*)")
                            .single()
                            .execute()
                            .value
                        
                        savedOrderItems.append(savedItem)
                        print("✅ Successfully saved item \(index + 1) with simplified payload: \(savedItem.id)")
                    } catch let retryError {
                        print("❌ Failed even with simplified payload for item \(index + 1): \(retryError)")
                        // Skip this item entirely - don't add duplicates
                        continue
                    }
                }
            }
            print("💾 Saved \(savedOrderItems.count)/\(items.count) items to database")
        } else {
            print("⚠️ No order items found in local order")
        }

        // Create final order with all items
        var finalOrder = createdOrder
        finalOrder.order_items = savedOrderItems
        finalOrder.total_amount = localOrder.total_amount

        print("Saved local draft order to database: \(finalOrder.id)")
        return finalOrder
    }

    @MainActor
    public func startNewOrder(tableId: String, guestCount: Int?) async throws -> Order {
        guard let restaurantId = supabaseManager.currentRestaurantId else {
            throw OrderManagerError.missingRestaurantId
        }
        guard let userId = supabaseManager.currentUser?.id else {
            // In a real app, user ID should always be available after login.
            // This might indicate an issue with session management or user data fetching.
            throw OrderManagerError.missingUserId
        }

        let newOrderPayload = NewOrderPayload(
            restaurant_id: restaurantId,
            table_id: tableId,
            session_id: userId.uuidString,
            guest_count: guestCount,
            status: ORDER_STATUS_DRAFT
        )

        do {
            let createdOrder: Order = try await supabaseManager.client
                .from("orders")
                .insert(newOrderPayload, returning: .representation)
                .select("*, table:tables(*), order_items(*, menu_item:menu_items(*))") // Fetch related data
                .single()
                .execute()
                .value

            self.currentDraftOrder = createdOrder
            print("Draft order started: \(createdOrder.id)")
            return createdOrder
        } catch {
            print("Error starting new order: \(error)")
            throw OrderManagerError.generalError("error_start_order".localized)
        }
    }

    @MainActor
    public func addItemToLocalDraftOrder(orderId: String, menuItemId: String, quantity: Int, notes: String?, selectedSizeId: MenuItemSizeId?, selectedToppingIds: [ToppingId]?, priceAtOrder: Double, menuItem: MenuItem) async throws -> OrderItem {
        print("🍽️ Adding item to local draft: \(menuItem.displayName), price: \(priceAtOrder), menuItem.price: \(menuItem.price)")
        // Check if this is a local draft order
        if let localOrder = localDraftOrders[orderId] {
            var updatedOrder = localOrder
            if updatedOrder.order_items == nil {
                updatedOrder.order_items = []
            }
            
            // Check if there's an existing item that can be grouped
            print("🔍 Checking for existing item to group: menuItemId=\(menuItemId), sizeId=\(selectedSizeId?.description ?? "nil"), toppings=\(selectedToppingIds?.description ?? "nil"), notes=\(notes ?? "nil")")
            
            let existingItemIndex = updatedOrder.order_items?.firstIndex { existingItem in
                let matches = existingItem.menu_item_id == menuItemId &&
                             existingItem.menu_item_size_id == selectedSizeId &&
                             existingItem.topping_ids == selectedToppingIds &&
                             existingItem.notes == notes
                if matches {
                    print("🔍 Found matching item: \(existingItem.id) with quantity \(existingItem.quantity)")
                }
                return matches
            }
            
            print("🔍 Current order has \(updatedOrder.order_items?.count ?? 0) items")
            
            let resultItem: OrderItem
            
            if let index = existingItemIndex {
                // Update existing item quantity — order_items is guaranteed non-nil here
                // because existingItemIndex was derived from order_items?.firstIndex
                var items = updatedOrder.order_items ?? []
                items[index].quantity += quantity
                items[index].updated_at = ISO8601DateFormatter().string(from: Date())
                updatedOrder.order_items = items
                resultItem = items[index]
            } else {
                // Create new item
                let newOrderItem = OrderItem(
                    id: UUID().uuidString,
                    restaurant_id: localOrder.restaurant_id,
                    order_id: orderId,
                    menu_item_id: menuItemId,
                    quantity: quantity,
                    notes: notes,
                    menu_item_size_id: selectedSizeId,
                    topping_ids: selectedToppingIds,
                    price_at_order: priceAtOrder,
                    status: .draft,
                    created_at: ISO8601DateFormatter().string(from: Date()),
                    updated_at: ISO8601DateFormatter().string(from: Date()),
                    menu_item: menuItem
                )
                updatedOrder.order_items?.append(newOrderItem)
                resultItem = newOrderItem
                print("Created new item: \(newOrderItem.id)")
            }
            
            // Recalculate total
            let total = updatedOrder.order_items?.reduce(0.0) { acc, item in
                acc + (item.price_at_order * Double(item.quantity))
            } ?? 0.0
            updatedOrder.total_amount = total
            
            // Update stored order
            localDraftOrders[orderId] = updatedOrder
            currentDraftOrder = updatedOrder
            
            return resultItem
        }
        
        // Fall back to database method for existing orders
        return try await addItemToDraftOrder(orderId: orderId, menuItemId: menuItemId, quantity: quantity, notes: notes, selectedSizeId: selectedSizeId, selectedToppingIds: selectedToppingIds, priceAtOrder: priceAtOrder)
    }

    @MainActor
    public func addItemToDraftOrder(orderId: String, menuItemId: String, quantity: Int, notes: String?, selectedSizeId: MenuItemSizeId?, selectedToppingIds: [ToppingId]?, priceAtOrder: Double) async throws -> OrderItem {

        guard let restaurantId = supabaseManager.currentRestaurantId else {
            throw OrderManagerError.missingRestaurantId
        }

        // Price calculation is now done in AddItemDetailView and passed as priceAtOrder.
        // The MOCK PRICE CALCULATION block has been removed.

        let newOrderItemPayload = NewOrderItemPayload(
            order_id: orderId,
            menu_item_id: menuItemId,
            quantity: quantity,
            notes: notes,
            restaurant_id: restaurantId,
            price_at_order: priceAtOrder, // Use the price calculated and passed by the view
            status: ORDER_ITEM_STATUS_DRAFT,
            menu_item_size_id: selectedSizeId,
            topping_ids: selectedToppingIds
        )

        do {
            let createdOrderItem: OrderItem = try await supabaseManager.client
                .from("order_items")
                .insert(newOrderItemPayload, returning: .representation)
                .select("*, menu_item:menu_items(*), menu_item_size:menu_item_sizes(*)") // Fetch related data
                .single()
                .execute()
                .value

            // Append to currentDraftOrder
            if currentDraftOrder?.id == orderId {
                currentDraftOrder?.order_items?.append(createdOrderItem)
                // Recalculate total price for the draft order
                recalculateCurrentDraftOrderTotal()
            } else {
                // If currentDraftOrder is not set or is different, fetch it to ensure consistency
                _ = try await getDraftOrder(orderId: orderId)
                currentDraftOrder?.order_items?.append(createdOrderItem)
                recalculateCurrentDraftOrderTotal()
            }

            print("Item added to draft order: \(createdOrderItem.id)")
            return createdOrderItem
        } catch {
            print("Error adding item to draft order: \(error)")
            throw OrderManagerError.generalError("error_add_item".localized)
        }
    }

    @MainActor
    private func recalculateCurrentDraftOrderTotal() {
        guard var draftOrder = currentDraftOrder, let items = draftOrder.order_items else { return }

        let total = items.reduce(0.0) { acc, item in
            acc + (item.price_at_order * Double(item.quantity))
        }
        draftOrder.total_amount = total
        currentDraftOrder = draftOrder

        // Optionally, update the order total in the database immediately for draft orders
        // This could be useful if another device needs to see the running total.
        // However, it might be better to do this only when confirming the order or explicitly saving a draft.
        // For now, we'll keep the total local until confirm/save.
    }


    @MainActor
    public func updateDraftOrderItem(orderItemId: String, newQuantity: Int, newNotes: String?) async throws -> OrderItem {
        // Note: This simplified version doesn't recalculate price_at_order if options change.
        // A full implementation would need to handle potential changes to selectedSize/selectedToppings
        // and refetch/recalculate price_at_order if they impact it.

        let updatePayload = UpdateOrderItemPayload(
            quantity: newQuantity,
            notes: newNotes
        )

        do {
            let updatedOrderItem: OrderItem = try await supabaseManager.client
                .from("order_items")
                .update(updatePayload)
                .eq("id", value: orderItemId)
                .select("*, menu_item:menu_items(*), menu_item_size:menu_item_sizes(*)")
                .single()
                .execute()
                .value

            // Update in currentDraftOrder
            if let index = currentDraftOrder?.order_items?.firstIndex(where: { $0.id == orderItemId }) {
                currentDraftOrder?.order_items?[index] = updatedOrderItem
                recalculateCurrentDraftOrderTotal()
            }
            print("Draft order item updated: \(updatedOrderItem.id)")
            return updatedOrderItem
        } catch {
            print("Error updating draft order item: \(error)")
            throw OrderManagerError.orderItemUpdateFailed(orderItemId)
        }
    }

    // Add a set to track items being updated to prevent race conditions
    private var itemsBeingUpdated: Set<String> = []
    
    @MainActor
    public func updateDraftOrderItemQuantity(orderItemId: String, newQuantity: Int) async throws {
        print("🔍 updateDraftOrderItemQuantity called - itemId: \(orderItemId), newQuantity: \(newQuantity)")
        
        // Prevent concurrent updates to the same item
        guard !itemsBeingUpdated.contains(orderItemId) else {
            print("⚠️ Item \(orderItemId) is already being updated, skipping")
            return
        }
        
        itemsBeingUpdated.insert(orderItemId)
        defer { itemsBeingUpdated.remove(orderItemId) }
        
        // Check if this is a local draft order item
        for orderId in localDraftOrders.keys {
            guard var localOrder = localDraftOrders[orderId] else { continue }
            
            if let itemIndex = localOrder.order_items?.firstIndex(where: { $0.id == orderItemId }) {
                print("🔍 Found item at index \(itemIndex), current quantity: \(localOrder.order_items?[itemIndex].quantity ?? 0)")
                
                // Ensure we have a mutable copy of the items array
                guard var items = localOrder.order_items else { 
                    print("❌ No order items found")
                    return 
                }
                
                print("🔍 Before update - Item ID: \(items[itemIndex].id), Quantity: \(items[itemIndex].quantity)")
                items[itemIndex].quantity = newQuantity
                items[itemIndex].updated_at = ISO8601DateFormatter().string(from: Date())
                print("🔍 After update - Item ID: \(items[itemIndex].id), Quantity: \(items[itemIndex].quantity)")
                localOrder.order_items = items
                
                // Recalculate total
                print("🔍 Recalculating total for \(items.count) items:")
                let total = items.reduce(0.0) { acc, item in
                    let itemTotal = item.price_at_order * Double(item.quantity)
                    print("🔍   Item: \(item.menu_item?.displayName ?? "Unknown") - price: \(item.price_at_order) x qty: \(item.quantity) = \(itemTotal)")
                    return acc + itemTotal
                }
                print("🔍 Final total: \(total)")
                localOrder.total_amount = total
                
                // Update both the dictionary and current draft
                localDraftOrders[orderId] = localOrder
                if currentDraftOrder?.id == orderId {
                    currentDraftOrder = localOrder
                }
                
                print("✅ Updated item quantity - itemId: \(orderItemId), new quantity: \(newQuantity), new total: \(total)")
                return
            }
        }
        
        print("🔍 Item not found in local orders, trying database")
        // Fall back to database method for existing orders
        try await updateDraftOrderItem(orderItemId: orderItemId, newQuantity: newQuantity, newNotes: nil)
    }

    @MainActor
    public func removeDraftOrderItem(orderItemId: String) async throws {
        // Check if this is a local draft order item
        for orderId in localDraftOrders.keys {
            guard var localOrder = localDraftOrders[orderId] else { continue }
            
            if let itemIndex = localOrder.order_items?.firstIndex(where: { $0.id == orderItemId }) {
                localOrder.order_items?.remove(at: itemIndex)
                
                // Recalculate total
                let total = localOrder.order_items?.reduce(0.0) { acc, item in
                    acc + (item.price_at_order * Double(item.quantity))
                } ?? 0.0
                localOrder.total_amount = total
                
                // Update both the dictionary and current draft
                localDraftOrders[orderId] = localOrder
                if currentDraftOrder?.id == orderId {
                    currentDraftOrder = localOrder
                }
                
                print("Removed item from local draft order: \(orderItemId)")
                return
            }
        }
        
        // Fall back to database removal for existing orders
        do {
            try await supabaseManager.client
                .from("order_items")
                .delete()
                .eq("id", value: orderItemId)
                .execute()

            // Remove from currentDraftOrder
            currentDraftOrder?.order_items?.removeAll(where: { $0.id == orderItemId })
            recalculateCurrentDraftOrderTotal()
            print("Draft order item removed: \(orderItemId)")
        } catch {
            print("Error removing draft order item: \(error)")
            throw OrderManagerError.generalError("error_remove_item".localized)
        }
    }

    @MainActor
    public func clearDraftOrder(orderId: String) async throws {
        // Check if this is a local draft order
        if localDraftOrders[orderId] != nil {
            localDraftOrders.removeValue(forKey: orderId)
            if currentDraftOrder?.id == orderId {
                currentDraftOrder = nil
            }
            print("Cleared local draft order: \(orderId)")
            return
        }
        
        // Ensure this order is the current draft before clearing locally
        if currentDraftOrder?.id != orderId {
             _ = try? await getDraftOrder(orderId: orderId) // Load it if not current
        }

        do {
            // 1. Delete all order_items associated with the orderId
            try await supabaseManager.client
                .from("order_items")
                .delete()
                .eq("order_id", value: orderId)
                .execute()
            print("Deleted items for draft order: \(orderId)")

            // 2. Delete the order itself
            try await supabaseManager.client
                .from("orders")
                .delete()
                .eq("id", value: orderId)
                .execute()
            print("Deleted draft order: \(orderId)")

            // Clear local state if it was the current draft
            if currentDraftOrder?.id == orderId {
                currentDraftOrder = nil
            }
        } catch {
            print("Error clearing draft order: \(error)")
            throw OrderManagerError.generalError("error_clear_draft".localized)
        }
    }

    @MainActor
    public func confirmOrderToKitchen(orderId: String) async throws -> Order {
        var orderToConfirm: Order
        
        // Check if this is a local draft order that needs to be saved to database first
        if let localOrder = localDraftOrders[orderId] {
            // Save local order to database
            orderToConfirm = try await saveLocalOrderToDatabase(localOrder)
            // Remove from local storage
            localDraftOrders.removeValue(forKey: orderId)
        } else if let currentOrder = currentDraftOrder, currentOrder.id == orderId {
            orderToConfirm = currentOrder
        } else {
            // Fetch the order from database
            if let fetchedOrder = try await getDraftOrder(orderId: orderId, forceFetch: true) {
                orderToConfirm = fetchedOrder
            } else {
                throw OrderManagerError.orderUpdateFailed("Order \(orderId) not found for confirmation.")
            }
        }

        // Recalculate total price one last time based on current items, just in case.
        let finalTotalPrice = orderToConfirm.order_items?.reduce(0.0) { $0 + ($1.price_at_order * Double($1.quantity)) } ?? 0

        // Create a proper Codable struct for the update payload
        struct OrderUpdatePayload: Codable {
            let status: String
            let total_amount: Double
            let updated_at: String
        }
        
        let updatePayload = OrderUpdatePayload(
            status: "new", // Change status to "new" or similar for kitchen
            total_amount: finalTotalPrice,
            updated_at: ISO8601DateFormatter().string(from: Date())
        )

        do {
            let confirmedOrder: Order = try await supabaseManager.client
                .from("orders")
                .update(updatePayload)
                .eq("id", value: orderToConfirm.id) // Use the correct order ID
                .select("*, table:tables(*), order_items(*, menu_item:menu_items(*), menu_item_size:menu_item_sizes(*))")
                .single()
                .execute()
                .value

            // Clear the local draft order state as it's no longer a draft
            currentDraftOrder = nil

            // Optionally, add to the main `orders` list if it's now an active order
            // Or rely on real-time updates / next fetchActiveOrders to pick it up.
            // For immediate UI update, consider adding it:
            if !self.orders.contains(where: { $0.id == confirmedOrder.id }) {
                 self.orders.insert(confirmedOrder, at: 0) // Add to top
            }

            print("Order confirmed to kitchen: \(confirmedOrder.id)")
            return confirmedOrder
        } catch {
            print("Error confirming order to kitchen: \(error)")
            throw OrderManagerError.orderUpdateFailed(orderId)
        }
    }

    @MainActor
    public func getDraftOrder(orderId: String, forceFetch: Bool = false) async throws -> Order? {
        // First check if this is a local draft order
        if let localOrder = localDraftOrders[orderId] {
            print("Returning local draft order for id: \(orderId)")
            currentDraftOrder = localOrder
            return localOrder
        }
        
        if !forceFetch, let currentDraft = currentDraftOrder, currentDraft.id == orderId {
            // If we have a cached version and not forcing fetch, return it.
            // However, if its items are nil or empty, it might be an incompletely loaded order.
            // A more robust cache would check if items are also populated.
            // For now, this basic cache stands.
            print("Returning cached currentDraftOrder for id: \(orderId)")
            return currentDraft
        }
        // If orderId is "previewOrder123" or similar, it implies a preview context.
        // For robust previews that don't rely on DB state, construct a full mock Order here.
        if orderId.starts(with: "previewOrder") || orderId == "mockDraftOrder123" { // Adjusted for DraftOrderView preview
            print("getDraftOrder constructing MOCK for orderId: \(orderId)")
            // Create mock MenuItems for more realistic OrderItems in the preview
            let mockCat = Category(id: "cat_mock_drinks", name_en: "Mock Drinks", name_ja: nil, name_vi: nil, position: 1)
            let mockMenuItem1 = MenuItem(id: "menuItem1_mock_preview", restaurant_id: "resto_preview", category_id: mockCat.id, name_en: "Mock Coffee", name_ja: nil, name_vi: nil, code: "MC01", description_en: "A warm mock coffee", description_ja: nil, description_vi: nil, price: 3.00, tags: nil, image_url: nil, stock_level: nil, available: true, position: 1, created_at: Date().ISO8601Format(), updated_at: Date().ISO8601Format(), category: mockCat, availableSizes: nil, availableToppings: nil)
            let mockMenuItem2 = MenuItem(id: "menuItem2_mock_preview", restaurant_id: "resto_preview", category_id: mockCat.id, name_en: "Mock Tea", name_ja: nil, name_vi: nil, code: "MT01", description_en: "A soothing mock tea", description_ja: nil, description_vi: nil, price: 2.50, tags: nil, image_url: nil, stock_level: nil, available: true, position: 2, created_at: Date().ISO8601Format(), updated_at: Date().ISO8601Format(), category: mockCat, availableSizes: nil, availableToppings: nil)

            let mockItem1 = OrderItem(id: "mockPreviewItem1", restaurant_id: "resto_preview", order_id: orderId, menu_item_id: mockMenuItem1.id, quantity: 2, notes: "Extra hot", menu_item_size_id: nil, topping_ids: nil, price_at_order: 3.00, status: .draft, created_at: Date().ISO8601Format(), updated_at: Date().ISO8601Format(), menu_item: mockMenuItem1)
            let mockItem2 = OrderItem(id: "mockPreviewItem2", restaurant_id: "resto_preview", order_id: orderId, menu_item_id: mockMenuItem2.id, quantity: 1, notes: nil, menu_item_size_id: nil, topping_ids: nil, price_at_order: 2.50, status: .draft, created_at: Date().ISO8601Format(), updated_at: Date().ISO8601Format(), menu_item: mockMenuItem2)

            let mockTable = Table(
                id: "table_mock_preview_om", restaurant_id: "resto_preview", name: "Preview Tbl OM", status: .occupied,
                capacity: 2, is_outdoor: false, is_accessible: true, notes: nil, qr_code: nil,
                created_at: Date().ISO8601Format(), updated_at: Date().ISO8601Format()
            )

            let mockOrderInstance = Order(
                id: orderId, restaurant_id: "resto_preview", table_id: mockTable.id,
                session_id: "session_preview", guest_count: 2, status: .draft, total_amount: 8.50, // 2*3.00 + 2.50
                order_number: Int.random(in: 100...200), created_at: Date().ISO8601Format(), updated_at: Date().ISO8601Format(),
                table: mockTable, order_items: [mockItem1, mockItem2],
                payment_method: nil, discount_amount: nil, tax_amount: nil, tip_amount: nil
            )
            self.currentDraftOrder = mockOrderInstance
            return mockOrderInstance
        }
        print("Fetching draft order \(orderId) from database.")
        do {
            let orderResponse: [Order] = try await supabaseManager.client
                .from("orders")
                .select("*, table:tables(*), order_items(*, menu_item:menu_items(*, category:categories(*)), menu_item_size:menu_item_sizes(*))") // Added category to menu_item
                .eq("id", value: orderId)
                .eq("status", value: "draft") // Ensure it's still a draft
                .limit(1)
                .execute()
                .value

            if let order = orderResponse.first {
                self.currentDraftOrder = order
                return order
            } else {
                // No draft order found, which is a valid case.
                return nil
            }
        } catch {
            print("Error fetching draft order \(orderId): \(error)")
            throw OrderManagerError.generalError(String(format: "error_get_draft".localized, orderId))
        }
    }
    
    // MARK: - Auto-printing Settings
    
    private func loadAutoPrintingSettings() {
        autoPrintingEnabled = UserDefaults.standard.object(forKey: "auto_printing_enabled") as? Bool ?? false
    }
    
    func setAutoPrintingEnabled(_ enabled: Bool) {
        autoPrintingEnabled = enabled
        UserDefaults.standard.set(enabled, forKey: "auto_printing_enabled")
    }
    
    // MARK: - Authentication Monitoring
    private func setupAuthenticationMonitoring() {
        // Listen for authentication state changes
        supabaseManager.$isAuthenticated
            .combineLatest(supabaseManager.$currentRestaurant)
            .sink { [weak self] (isAuthenticated, restaurant) in
                // Use Task to bridge async context
                Task { @MainActor in
                    if isAuthenticated && restaurant != nil {
                        await self?.onAuthenticationSuccess()
                    } else {
                        await self?.onAuthenticationLost()
                    }
                }
            }
            .store(in: &cancellables)
    }
    
    @MainActor
    private func onAuthenticationSuccess() async {
        print("Authentication successful - setting up OrderManager")
        await setupRealtimeSubscription()
        await fetchActiveOrders()
    }
    
    @MainActor
    private func onAuthenticationLost() async {
        print("Authentication lost - cleaning up OrderManager")
        await cleanupRealtimeSubscription()
        orders = []
        errorMessage = "error_not_authenticated".localized
        isRealtimeConnected = false
    }
    
    // MARK: - Fetch Orders
    @MainActor
    func fetchActiveOrders() async {
        guard supabaseManager.isAuthenticated else {
            errorMessage = "error_not_authenticated".localized
            print("Cannot fetch orders - user not authenticated")
            return
        }
        
        guard let restaurantId = supabaseManager.currentRestaurantId else {
            errorMessage = "error_no_restaurant_id".localized
            print("Cannot fetch orders - no restaurant ID")
            return
        }
        
        isLoading = true
        errorMessage = nil
        
        do {
            // A single query to fetch all required data
            let response: [OrderWithTableResponse] = try await supabaseManager.client
                .from("orders")
                .select("""
                    *,
                    table:tables(*),
                    order_items(
                        *,
                        menu_item:menu_items(
                            *,
                            category:categories(
                                id,
                                name_en,
                                name_ja,
                                name_vi
                            )
                        ),
                        menu_item_size:menu_item_sizes(*)
                    )
                """)
                .eq("restaurant_id", value: restaurantId)
                .in("status", value: ["new", "serving"])
                .order("created_at", ascending: false)
                .execute()
                .value

            self.orders = response.map { $0.toOrder() }
            print("Fetched \(orders.count) active orders in a single query")
            
        } catch {
            print("Error fetching active orders: \(error)")
            errorMessage = "error_fetch_active_orders".localized
        }
        
        isLoading = false
    }
    
    // Add missing fetchAllOrders method
    @MainActor
    func fetchAllOrders() async {
        guard supabaseManager.isAuthenticated else {
            errorMessage = "error_not_authenticated".localized
            print("Cannot fetch all orders - user not authenticated")
            return
        }
        
        guard let restaurantId = supabaseManager.currentRestaurantId else {
            errorMessage = "error_no_restaurant_id".localized
            print("Cannot fetch all orders - no restaurant ID")
            return
        }
        
        isLoading = true
        errorMessage = nil
        
        do {
            let response: [OrderWithTableResponse] = try await supabaseManager.client
                .from("orders")
                .select("""
                    *,
                    table:tables(*),
                    order_items(
                        *,
                        menu_item:menu_items(
                            *,
                            category:categories(
                                id,
                                name_en,
                                name_ja,
                                name_vi
                            )
                        ),
                        menu_item_size:menu_item_sizes(*)
                    )
                """)
                .eq("restaurant_id", value: restaurantId)
                .order("created_at", ascending: false)
                .execute()
                .value
            
            self.allOrders = response.map { $0.toOrder() }
            print("Fetched \(allOrders.count) total orders")
            
        } catch {
            print("Error fetching all orders: \(error)")
            errorMessage = "error_fetch_all_orders".localized
        }
        
        isLoading = false
    }
    
    // MARK: - Update Order Status
    @MainActor
    func updateOrderStatus(orderId: String, newStatus: OrderStatus) async throws {
        do {
            // Use a simple update without expecting the full object back
            let _ = try await supabaseManager.client
                .from("orders")
                .update([
                    "status": newStatus.rawValue,
                    "updated_at": ISO8601DateFormatter().string(from: Date())
                ])
                .eq("id", value: orderId)
                .execute()
            
            // Update local state
            if let index = orders.firstIndex(where: { $0.id == orderId }) {
                orders[index].status = newStatus
                orders[index].updated_at = ISO8601DateFormatter().string(from: Date())
                
                // If order is completed, remove it from the list
                if newStatus == .completed {
                    orders.remove(at: index)
                }
            }
            
            // Also update in allOrders if needed
            if let allIndex = allOrders.firstIndex(where: { $0.id == orderId }) {
                allOrders[allIndex].status = newStatus
                allOrders[allIndex].updated_at = ISO8601DateFormatter().string(from: Date())
            }
            
            print("Updated order status to \(newStatus.rawValue)")
            
        } catch {
            print("Error updating order status: \(error)")
            throw error
        }
    }

    @MainActor
    func completeCheckout(
        orderId: String,
        paymentMethod: String,
        discountAmount: Double,
        taxAmount: Double,
        tipAmount: Double,
        totalAmount: Double
    ) async throws {
        struct CheckoutUpdatePayload: Codable {
            let status: String
            let total_amount: Double
            let updated_at: String
        }

        let updatedAt = ISO8601DateFormatter().string(from: Date())
        let payload = CheckoutUpdatePayload(
            status: OrderStatus.completed.rawValue,
            total_amount: totalAmount,
            updated_at: updatedAt
        )

        do {
            let _ = try await supabaseManager.client
                .from("orders")
                .update(payload)
                .eq("id", value: orderId)
                .execute()

            if let index = orders.firstIndex(where: { $0.id == orderId }) {
                orders[index].status = .completed
                orders[index].payment_method = paymentMethod
                orders[index].discount_amount = discountAmount
                orders[index].tax_amount = taxAmount
                orders[index].tip_amount = tipAmount
                orders[index].total_amount = totalAmount
                orders[index].updated_at = updatedAt
                orders.remove(at: index)
            }

            if let index = allOrders.firstIndex(where: { $0.id == orderId }) {
                allOrders[index].status = .completed
                allOrders[index].payment_method = paymentMethod
                allOrders[index].discount_amount = discountAmount
                allOrders[index].tax_amount = taxAmount
                allOrders[index].tip_amount = tipAmount
                allOrders[index].total_amount = totalAmount
                allOrders[index].updated_at = updatedAt
            }
        } catch {
            print("Error completing checkout: \(error)")
            throw error
        }
    }
    
    // MARK: - Update Order Item Notes
    @MainActor
    func updateOrderItemNotes(orderItemId: String, notes: String?) async throws {
        do {
            let _: OrderItem = try await supabaseManager.client
                .from("order_items")
                .update([
                    "notes": notes // Optional String is already Encodable, no need for Any
                ])
                .eq("id", value: orderItemId)
                .single()
                .execute()
                .value
            
            // Update local state
            for (orderIndex, order) in orders.enumerated() {
                if let orderItems = order.order_items,
                   let itemIndex = orderItems.firstIndex(where: { $0.id == orderItemId }) {
                    var item = orderItems[itemIndex]
                    item.notes = notes
                    orders[orderIndex].order_items?[itemIndex] = item
                    break
                }
            }
            
            print("Updated order item notes")
            
        } catch {
            print("Error updating order item notes: \(error)")
            throw OrderManagerError.orderItemUpdateFailed("error_update_item_notes".localized)
        }
    }
    
    // MARK: - Cancel Order Item
    @MainActor
    func cancelOrderItem(orderItemId: String) async throws {
        do {
            // Set status to canceled
            let canceledItem: OrderItem = try await supabaseManager.client
                .from("order_items")
                .update([
                    "status": OrderItemStatus.canceled.rawValue,
                    "updated_at": ISO8601DateFormatter().string(from: Date())
                ])
                .eq("id", value: orderItemId)
                .single()
                .execute()
                .value
            
            // Update local state
            for (orderIndex, order) in orders.enumerated() {
                if let orderItems = order.order_items,
                   let itemIndex = orderItems.firstIndex(where: { $0.id == orderItemId }) {
                    var item = orderItems[itemIndex]
                    item.status = .canceled
                    item.updated_at = ISO8601DateFormatter().string(from: Date())
                    orders[orderIndex].order_items?[itemIndex] = item
                    break
                }
            }

            for (orderIndex, order) in allOrders.enumerated() {
                if let orderItems = order.order_items,
                   let itemIndex = orderItems.firstIndex(where: { $0.id == orderItemId }) {
                    var item = orderItems[itemIndex]
                    item.status = .canceled
                    item.updated_at = ISO8601DateFormatter().string(from: Date())
                    allOrders[orderIndex].order_items?[itemIndex] = item
                    break
                }
            }

            if let orderId = orderId(forItemId: orderItemId, fallback: canceledItem.order_id) {
                try await syncOrderFinancialsFromItems(orderId: orderId)
                try await syncOrderStatusFromItems(orderId: orderId)
            }
            
            print("canceled order item: \(orderItemId)")
            
        } catch {
            print("Error cancelling order item: \(error)")
            throw OrderManagerError.orderItemUpdateFailed("error_cancel_item".localized)
        }
    }

    // MARK: - Update Order Item Status
    @MainActor
    func updateOrderItemStatus(orderItemId: String, newStatus: OrderItemStatus) async throws {
        do {
            let updatedItem: OrderItem = try await supabaseManager.client
                .from("order_items")
                .update([
                    "status": newStatus.rawValue,
                    "updated_at": ISO8601DateFormatter().string(from: Date())
                ])
                .eq("id", value: orderItemId)
                .single()
                .execute()
                .value
            
            // Update local state
            for (orderIndex, order) in orders.enumerated() {
                if let orderItems = order.order_items,
                   let itemIndex = orderItems.firstIndex(where: { $0.id == orderItemId }) {
                    var item = orderItems[itemIndex]
                    item.status = newStatus
                    orders[orderIndex].order_items?[itemIndex] = item
                    break
                }
            }

            if let orderId = orderId(forItemId: orderItemId, fallback: updatedItem.order_id) {
                try await syncOrderStatusFromItems(orderId: orderId)
            }
            
            print("Updated order item status to \(newStatus.rawValue)")
            
        } catch {
            print("Error updating order item status: \(error)")
            throw OrderManagerError.orderItemUpdateFailed("error_update_item_status".localized)
        }
    }

    func operationalStatus(for table: Table) -> TableOperationalStatus {
        switch table.status {
        case .reserved:
            return .reserved
        case .maintenance:
            return .maintenance
        case .available, .occupied:
            break
        }

        let activeOrders = mergedOrders().filter { order in
            order.table_id == table.id && order.status != .completed && order.status != .canceled
        }

        guard !activeOrders.isEmpty else {
            return TableOperationalStatus(baseStatus: table.status)
        }

        let hasServingOrder = activeOrders.contains { order in
            if order.status == .serving {
                return true
            }

            return (order.order_items ?? []).contains { item in
                item.status == .preparing || item.status == .ready || item.status == .served
            }
        }

        return hasServingOrder ? .serving : .occupied
    }

    private func mergedOrders() -> [Order] {
        var deduped: [String: Order] = [:]

        for order in allOrders {
            deduped[order.id] = order
        }

        for order in orders {
            deduped[order.id] = order
        }

        return Array(deduped.values)
    }

    private func orderId(forItemId orderItemId: String, fallback: String) -> String? {
        for order in mergedOrders() {
            if order.order_items?.contains(where: { $0.id == orderItemId }) == true {
                return order.id
            }
        }

        return fallback.isEmpty ? nil : fallback
    }

    @MainActor
    private func syncOrderFinancialsFromItems(orderId: String) async throws {
        guard let order = mergedOrders().first(where: { $0.id == orderId }) else {
            return
        }

        let subtotal = order.activeItems.reduce(0.0) { partial, item in
            partial + (item.price_at_order * Double(item.quantity))
        }
        let updatedAt = ISO8601DateFormatter().string(from: Date())
        struct OrderFinancialUpdatePayload: Codable {
            let total_amount: Double
            let updated_at: String
        }

        let _ = try await supabaseManager.client
            .from("orders")
            .update(OrderFinancialUpdatePayload(total_amount: subtotal, updated_at: updatedAt))
            .eq("id", value: orderId)
            .execute()

        applyOrderFinancialsLocally(orderId: orderId, subtotal: subtotal, updatedAt: updatedAt)
    }

    @MainActor
    private func syncOrderStatusFromItems(orderId: String) async throws {
        guard let order = mergedOrders().first(where: { $0.id == orderId }) else {
            return
        }

        let derivedStatus = derivedStatus(for: order)
        guard derivedStatus != order.status else {
            return
        }

        let updatedAt = ISO8601DateFormatter().string(from: Date())

        let _ = try await supabaseManager.client
            .from("orders")
            .update([
                "status": derivedStatus.rawValue,
                "updated_at": updatedAt
            ])
            .eq("id", value: orderId)
            .execute()

        applyOrderStatusLocally(orderId: orderId, newStatus: derivedStatus, updatedAt: updatedAt)
    }

    private func derivedStatus(for order: Order) -> OrderStatus {
        if order.status == .completed {
            return .completed
        }

        if order.status == .canceled {
            let hasActiveItems = (order.order_items ?? []).contains { $0.status != .canceled }
            if !hasActiveItems {
                return .canceled
            }
        }

        let items = order.order_items ?? []
        let activeItems = items.filter { $0.status != .canceled }

        if activeItems.isEmpty {
            return .canceled
        }

        let hasStartedService = activeItems.contains { item in
            item.status == .preparing || item.status == .ready || item.status == .served
        }

        return hasStartedService ? .serving : .new
    }

    private func applyOrderStatusLocally(orderId: String, newStatus: OrderStatus, updatedAt: String) {
        if let index = orders.firstIndex(where: { $0.id == orderId }) {
            orders[index].status = newStatus
            orders[index].updated_at = updatedAt
        }

        if let index = allOrders.firstIndex(where: { $0.id == orderId }) {
            allOrders[index].status = newStatus
            allOrders[index].updated_at = updatedAt
        }
    }

    private func applyOrderFinancialsLocally(orderId: String, subtotal: Double, updatedAt: String) {
        if let index = orders.firstIndex(where: { $0.id == orderId }) {
            orders[index].total_amount = subtotal
            orders[index].updated_at = updatedAt
        }

        if let index = allOrders.firstIndex(where: { $0.id == orderId }) {
            allOrders[index].total_amount = subtotal
            allOrders[index].updated_at = updatedAt
        }
    }
    
    // MARK: - Realtime Subscription Management
    private func setupRealtimeSubscription() async {
        // Clean up any existing subscription first
        await cleanupRealtimeSubscription()
        
        guard supabaseManager.isAuthenticated else {
            print("Cannot setup realtime subscription - user not authenticated")
            return
        }
        
        guard let restaurantId = supabaseManager.currentRestaurantId else {
            print("Cannot setup realtime subscription - no restaurant ID")
            return
        }
        
        print("Setting up realtime subscription for restaurant: \(restaurantId)")
        
        realtimeChannel = supabaseManager.client.realtimeV2.channel("orders-\(restaurantId)")
        
        // Listen for order insertions
        if let ordersInsertion = realtimeChannel?.postgresChange(
            InsertAction.self,
            schema: "public",
            table: "orders",
            filter: "restaurant_id=eq.\(restaurantId)"
        ) {
            Task { [weak self] in
                for await _ in ordersInsertion {
                    print("New order inserted via realtime")
                    await MainActor.run {
                        Task { @MainActor in
                            await self?.handleOrderChange()
                        }
                    }
                }
            }
        }
        // Listen for order updates
        if let ordersUpdate = realtimeChannel?.postgresChange(
            UpdateAction.self,
            schema: "public",
            table: "orders",
            filter: "restaurant_id=eq.\(restaurantId)"
        ) {
            Task { [weak self] in
                for await _ in ordersUpdate {
                    print("Order updated via realtime")
                    await MainActor.run {
                        Task { @MainActor in
                            await self?.handleOrderChange()
                        }
                    }
                }
            }
        }
        // Listen for order item updates
        if let orderItemsUpdate = realtimeChannel?.postgresChange(
            UpdateAction.self,
            schema: "public",
            table: "order_items"
        ) {
            Task { [weak self] in
                for await _ in orderItemsUpdate {
                    print("Order item updated via realtime")
                    await MainActor.run {
                        Task { @MainActor in
                            await self?.handleOrderItemChange()
                        }
                    }
                }
            }
        }
        // Listen for subscription status
        if let channel = realtimeChannel {
            Task { [weak self] in
                await channel.subscribe()
                await MainActor.run {
                    self?.isRealtimeConnected = true
                }
            }
        }
    }
    
    private func cleanupRealtimeSubscription() async {
        if let channel = realtimeChannel {
            await channel.unsubscribe()
            realtimeChannel = nil
            print("Cleaned up realtime subscription")
        }
        await MainActor.run {
            isRealtimeConnected = false
        }
    }
    
    @MainActor
    private func handleOrderChange() async {
        let previousOrders = orders
        print("📋 Order change detected: previous=\(previousOrders.count), fetching fresh data...")
        await fetchActiveOrders()
        print("📋 After fetch: current=\(orders.count)")
        
        let canAutoPrint = hasKitchenPrinter()
        
        // Check for new orders to auto-print
        if orders.count > previousOrders.count {
            triggerFeedback()
            
            let newOrderCount = orders.count - previousOrders.count
            print("🆕 Detected \(newOrderCount) new order(s)")
            print("🖨️ Auto-print check: enabled=\(autoPrintingEnabled), hasKitchenPrinter=\(canAutoPrint)")
            
            // Auto-print new orders if enabled and kitchen printer is configured
            if autoPrintingEnabled && canAutoPrint {
                print("🖨️ Triggering auto-print for new orders")
                await autoPrintNewOrders(previousOrders: previousOrders)
            } else {
                print("🖨️ Auto-print skipped - enabled: \(autoPrintingEnabled), canPrint: \(canAutoPrint)")
            }
        } else if orders.count == previousOrders.count {
            print("📋 No new orders detected (same count), checking for new items...")
            
            // Check for new items added to existing orders
            let newItems = findNewItemsInExistingOrders(currentOrders: orders, previousOrders: previousOrders)
            
            if !newItems.isEmpty {
                print("🍽️ Detected \(newItems.count) new item(s) in existing orders")
                triggerFeedback()
                
                if autoPrintingEnabled && canAutoPrint {
                    print("🖨️ Triggering auto-print for new items")
                    await autoPrintNewItems(newItems)
                } else {
                    print("🖨️ Auto-print skipped for items - enabled: \(autoPrintingEnabled), canPrint: \(canAutoPrint)")
                }
            } else {
                print("📋 No new items detected")
            }
        } else {
            print("📋 Order count decreased (completed/canceled orders?)")
        }
    }
    
    @MainActor
    private func handleOrderItemChange() async {
        let previousOrders = orders
        
        // Refresh orders when order items change
        await fetchActiveOrders()
        
        // Check for items changing to "ready" status for auto-printing
        if autoPrintingEnabled && hasKitchenPrinter() {
            await autoPrintReadyItems(previousOrders: previousOrders)
        }
    }
    
    // MARK: - Public Methods for Manual Control
    @MainActor
    func refreshOrders() async {
        await fetchActiveOrders()
    }
    
    @MainActor
    func reconnectRealtime() async {
        await setupRealtimeSubscription()
    }

    private func triggerFeedback() {
        #if os(iOS)
        let generator = UINotificationFeedbackGenerator()
        generator.notificationOccurred(.success)
        #endif
    }
    
    // MARK: - Auto-printing Methods
    
    private func hasKitchenPrinter() -> Bool {
        let settingsManager = PrinterSettingsManager.shared
        
        print("🖨️ Checking printer availability:")
        print("  - Printer mode: \(settingsManager.printerMode)")
        print("  - Active printer: \(settingsManager.activePrinter?.name ?? "none")")
        print("  - Configured printers count: \(settingsManager.configuredPrinters.count)")
        print("  - Using default printer: \(settingsManager.isUsingDefaultPrinter())")
        print("  - Has kitchen printer: \(settingsManager.hasKitchenPrinter())")
        
        // In single printer mode, any configured printer can print kitchen orders
        if settingsManager.printerMode == .single {
            let result = settingsManager.activePrinter != nil || 
                        !settingsManager.configuredPrinters.isEmpty || 
                        settingsManager.isUsingDefaultPrinter()
            print("  - Single mode result: \(result)")
            return result
        }
        
        // In dual printer mode, need a specific kitchen printer
        let result = settingsManager.hasKitchenPrinter()
        print("  - Dual mode result: \(result)")
        return result
    }
    
    @MainActor
    private func autoPrintNewOrders(previousOrders: [Order]) async {
        await withCheckedContinuation { (continuation: CheckedContinuation<Void, Never>) in
            autoPrintQueue.async {
                Task {
                    await self.performAutoPrintNewOrders(previousOrders: previousOrders)
                    continuation.resume()
                }
            }
        }
    }
    
    private func performAutoPrintNewOrders(previousOrders: [Order]) async {
        let newOrders = findNewOrders(currentOrders: orders, previousOrders: previousOrders)
        
        guard !newOrders.isEmpty else { return }
        
        await MainActor.run {
            autoPrintingInProgress = true
        }
        
        for order in newOrders {
            // Skip if already printed
            if printedNewOrders.contains(order.id) {
                continue
            }
            
            // Only print if order has items
            guard let items = order.order_items, !items.isEmpty else {
                continue
            }
            
            do {
                // Use the shared PrinterManager instance instead of creating a new one
                try await printerManager.printKitchenSlip(for: order)
                printedNewOrders.insert(order.id)
                await MainActor.run {
                    autoPrintStats.recordNewOrderPrint()
                }
                
                let tableInfo = order.table?.name ?? String(format: "orders_table_prefix".localized, order.table_id)
                await MainActor.run {
                    lastAutoPrintResult = String(format: "autoprint_success_new_order".localized, tableInfo)
                }
                print("Auto-printed new order: \(order.id) for \(tableInfo)")
                
            } catch {
                await MainActor.run {
                    autoPrintStats.recordPrintFailure()
                    lastAutoPrintResult = "autoprint_failure".localized
                }
                print("Auto-print failed for new order \(order.id): \(error)")
            }
        }
        
        await MainActor.run {
            autoPrintingInProgress = false
        }
        
        // Clear the result message after 5 seconds
        Task {
            try? await Task.sleep(nanoseconds: 5_000_000_000)
            await MainActor.run {
                lastAutoPrintResult = nil
            }
        }
    }
    
    @MainActor
    private func autoPrintNewItems(_ newItems: [(OrderItem, Order)]) async {
        await withCheckedContinuation { (continuation: CheckedContinuation<Void, Never>) in
            autoPrintQueue.async {
                Task {
                    await self.performAutoPrintNewItems(newItems)
                    continuation.resume()
                }
            }
        }
    }
    
    private func performAutoPrintNewItems(_ newItems: [(OrderItem, Order)]) async {
        guard !newItems.isEmpty else { return }
        
        await MainActor.run {
            autoPrintingInProgress = true
        }
        
        for (item, order) in newItems {
            // Skip if already printed
            if printedNewItems.contains(item.id) {
                print("⏭️ Skipping already printed item: \(item.id)")
                continue
            }
            
            do {
                // Print individual item slip
                try await printNewItemSlip(item: item, order: order)
                printedNewItems.insert(item.id) // Use dedicated tracking set
                await MainActor.run {
                    autoPrintStats.recordNewOrderPrint()
                }
                
                let itemName = item.menu_item?.displayName ?? "orders_unknown_item".localized
                let tableInfo = order.table?.name ?? String(format: "orders_table_prefix".localized, order.table_id)
                await MainActor.run {
                    lastAutoPrintResult = String(format: "autoprint_success_new_item".localized, itemName, tableInfo)
                }
                print("Auto-printed new item: \(item.id) - \(itemName)")
                
            } catch {
                await MainActor.run {
                    autoPrintStats.recordPrintFailure()
                    lastAutoPrintResult = "autoprint_failure".localized
                }
                print("Auto-print failed for new item \(item.id): \(error)")
            }
        }
        
        await MainActor.run {
            autoPrintingInProgress = false
        }
        
        // Clear the result message after 5 seconds
        Task {
            try? await Task.sleep(nanoseconds: 5_000_000_000)
            await MainActor.run {
                lastAutoPrintResult = nil
            }
        }
    }
    
    @MainActor
    private func printNewItemSlip(item: OrderItem, order: Order) async throws {
        let settingsManager = PrinterSettingsManager.shared
        let printerService = PrinterService.shared
        
        // Create proper ESC/POS formatted slip
        var outputData = Data()
        
        // Clear buffer and initialize printer properly
        outputData.append(Data(PrinterConfig.Commands.clearBuffer))
        outputData.append(Data(PrinterConfig.Commands.initialize))
        
        // Set charset based on print language
        switch settingsManager.printLanguage {
        case .vietnamese:
            outputData.append(Data(PrinterConfig.Commands.setCharsetCP1258))
        case .japanese:
            outputData.append(Data(PrinterConfig.Commands.setCharsetShiftJIS))
        case .english:
            outputData.append(Data(PrinterConfig.Commands.setCharsetCP1252))
        }
        
        // Header - Center aligned and bold
        outputData.append(Data(PrinterConfig.Commands.alignCenter))
        outputData.append(Data(PrinterConfig.Commands.boldOn))
        
        // Get encoding based on language
        let encoding: String.Encoding
        switch settingsManager.printLanguage {
        case .vietnamese:
            encoding = String.Encoding(rawValue: CFStringConvertEncodingToNSStringEncoding(CFStringEncoding(CFStringEncodings.windowsVietnamese.rawValue)))
        case .japanese:
            encoding = String.Encoding.shiftJIS
        case .english:
            encoding = String.Encoding.windowsCP1252
        }
        
        // Add leading spacing for better separation
        outputData.append("\n\n".data(using: encoding) ?? Data())
        
        outputData.append("=== NEW ITEM ADDED ===\n".data(using: encoding) ?? Data())
        outputData.append(Data(PrinterConfig.Commands.boldOff))
        outputData.append(Data(PrinterConfig.Commands.alignLeft))
        
        // Order info
        var orderInfo = ""
        orderInfo += "Order: \(order.table?.name ?? "Table \(order.table_id)")\n"
        if let orderNumber = order.order_number {
            orderInfo += "Order #: \(orderNumber)\n"
        }
        orderInfo += "Time: \(DateFormatter.localizedString(from: Date(), dateStyle: .none, timeStyle: .short))\n"
        orderInfo += String(repeating: "-", count: 32) + "\n"
        outputData.append(orderInfo.data(using: encoding) ?? Data())
        
        // Item details
        let itemName = item.menu_item?.displayName ?? "Unknown Item"
        var itemText = "\(item.quantity)x \(itemName)\n"
        
        if let notes = item.notes, !notes.isEmpty {
            itemText += "Note: \(notes)\n"
        }
        
        if let size = item.menu_item_size_id, !size.isEmpty {
            itemText += "Size: \(size)\n"
        }
        
        itemText += String(repeating: "=", count: 32) + "\n"
        itemText += "\n" // Extra spacing after content
        outputData.append(itemText.data(using: encoding) ?? Data())
        
        // Enhanced paper feeding and cutting sequence with proper spacing
        outputData.append(Data(PrinterConfig.Commands.paperFeedExtra)) // Extra feed for better spacing
        outputData.append("\n\n\n".data(using: encoding) ?? Data()) // Additional line feeds before cutting
        outputData.append(Data(PrinterConfig.Commands.cutPaperAdvanced)) // Advanced cut with feed
        
        // Use kitchen printer if configured, otherwise use default
        switch settingsManager.printerMode {
        case .single:
            try await printerService.connectAndSendData(data: outputData)
        case .dual:
            if let kitchenConfig = settingsManager.getKitchenPrinterConfig() {
                try await printerService.connectAndSendData(data: outputData, to: kitchenConfig)
            } else {
                try await printerService.connectAndSendData(data: outputData)
            }
        }
    }
    
    @MainActor
    private func autoPrintReadyItems(previousOrders: [Order]) async {
        let readyItems = findItemsChangedToReady(currentOrders: orders, previousOrders: previousOrders)
        
        guard !readyItems.isEmpty else { return }
        
        autoPrintingInProgress = true
        
        for item in readyItems {
            // Skip if already printed
            if printedReadyItems.contains(item.id) {
                continue
            }
            
            // Find the order containing this item
            guard let order = orders.first(where: { order in
                order.order_items?.contains(where: { $0.id == item.id }) == true
            }) else {
                continue
            }
            
            do {
                try await printItemOverview(item: item, order: order)
                printedReadyItems.insert(item.id)
                autoPrintStats.recordReadyItemPrint()
                
                let itemName = item.menu_item?.displayName ?? "orders_unknown_item".localized
                let tableInfo = order.table?.name ?? String(format: "orders_table_prefix".localized, order.table_id)
                lastAutoPrintResult = String(format: "autoprint_success_new_item".localized, itemName, tableInfo)
                
            } catch {
                autoPrintStats.recordPrintFailure()
                lastAutoPrintResult = "autoprint_failure".localized
                print("Auto-print failed for ready item \(item.id): \(error)")
            }
        }
        
        autoPrintingInProgress = false
        
        // Clear the result message after 5 seconds
        Task {
            try? await Task.sleep(nanoseconds: 5_000_000_000)
            lastAutoPrintResult = nil
        }
    }
    
    internal func findNewOrders(currentOrders: [Order], previousOrders: [Order]) -> [Order] {
        let previousOrderIds = Set(previousOrders.map { $0.id })
        return currentOrders.filter { !previousOrderIds.contains($0.id) }
    }
    
    internal func findNewItemsInExistingOrders(currentOrders: [Order], previousOrders: [Order]) -> [(OrderItem, Order)] {
        var newItems: [(OrderItem, Order)] = []
        
        // Create lookup dictionary for previous orders
        let previousOrderDict = Dictionary(uniqueKeysWithValues: previousOrders.map { ($0.id, $0) })
        
        for currentOrder in currentOrders {
            guard let previousOrder = previousOrderDict[currentOrder.id] else {
                // This is a new order, skip (handled by findNewOrders)
                continue
            }
            
            // Get previous item IDs for this order
            let previousItemIds = Set(previousOrder.order_items?.map { $0.id } ?? [])
            
            // Find new items in current order
            if let currentItems = currentOrder.order_items {
                for item in currentItems {
                    if !previousItemIds.contains(item.id) {
                        print("🍽️ Found new item: \(item.menu_item?.displayName ?? "Unknown") in order \(currentOrder.id)")
                        newItems.append((item, currentOrder))
                    }
                }
            }
        }
        
        return newItems
    }
    
    internal func findItemsChangedToReady(currentOrders: [Order], previousOrders: [Order]) -> [OrderItem] {
        var readyItems: [OrderItem] = []
        
        // Create lookup for previous order items
        var previousItemStatuses: [String: OrderItemStatus] = [:]
        for order in previousOrders {
            if let items = order.order_items {
                for item in items {
                    previousItemStatuses[item.id] = item.status
                }
            }
        }
        
        // Check current orders for items that changed to ready
        for order in currentOrders {
            if let items = order.order_items {
                for item in items {
                    if item.status == .ready {
                        let previousStatus = previousItemStatuses[item.id]
                        if previousStatus != .ready {
                            readyItems.append(item)
                        }
                    }
                }
            }
        }
        
        return readyItems
    }
    
    @MainActor
    private func printItemOverview(item: OrderItem, order: Order) async throws {
        let settingsManager = PrinterSettingsManager.shared
        let printerService = PrinterService.shared
        
        // Create a simple overview format for ready items
        var overview = "ITEM READY\n"
        overview += String(repeating: "=", count: 32) + "\n"
        overview += "Item: \(item.menu_item?.displayName ?? "Unknown Item")\n"
        overview += "Table: \(order.table?.name ?? "Table \(order.table_id)")\n"
        overview += "Quantity: \(item.quantity)\n"
        
        if let notes = item.notes, !notes.isEmpty {
            overview += "Notes: \(notes)\n"
        }
        
        overview += "Time: \(DateFormatter.localizedString(from: Date(), dateStyle: .none, timeStyle: .short))\n"
        overview += String(repeating: "=", count: 32) + "\n\n\n"
        
        let printData = Data(overview.utf8)
        
        // Use kitchen printer if configured, otherwise use default
        switch settingsManager.printerMode {
        case .single:
            try await printerService.connectAndSendData(data: printData)
        case .dual:
            if let kitchenConfig = settingsManager.getKitchenPrinterConfig() {
                try await printerService.connectAndSendData(data: printData, to: kitchenConfig)
            } else {
                try await printerService.connectAndSendData(data: printData)
            }
        }
    }
    
    // MARK: - Manual Testing Functions
    
    @MainActor
    public func testPrintLatestOrder() async {
        guard let latestOrder = orders.first else {
            print("❌ No orders available to print")
            return
        }
        
        print("🧪 Testing print for order: \(latestOrder.id)")
        do {
            try await printerManager.printKitchenSlip(for: latestOrder)
            print("✅ Manual print test successful")
        } catch {
            print("❌ Manual print test failed: \(error)")
        }
    }
    
    @MainActor
    public func testPrintNewItemSlip() async {
        guard let latestOrder = orders.first,
              let firstItem = latestOrder.order_items?.first else {
            print("❌ No orders or items available to print")
            return
        }
        
        print("🧪 Testing new item slip for: \(firstItem.menu_item?.displayName ?? "Unknown")")
        do {
            try await printNewItemSlip(item: firstItem, order: latestOrder)
            print("✅ Manual new item slip test successful")
        } catch {
            print("❌ Manual new item slip test failed: \(error)")
        }
    }
    
    // MARK: - Clear Print History (for testing/reset)
    
    func clearPrintHistory() {
        printedNewOrders.removeAll()
        printedReadyItems.removeAll()
        printedNewItems.removeAll()
        autoPrintStats.reset()
        lastAutoPrintResult = "kitchen_clear_print_history".localized
        
        // Clear the result message after 3 seconds
        Task {
            try? await Task.sleep(nanoseconds: 3_000_000_000)
            lastAutoPrintResult = nil
        }
    }
    
    // MARK: - Helper Functions
    // Ensure TimeoutError is defined if not already present, or use a general error.
    // struct TimeoutError: LocalizedError { ... } was present at the end of the original file.
    private func withTimeout<T>(seconds: TimeInterval, operation: @escaping () async throws -> T) async throws -> T {
        return try await withThrowingTaskGroup(of: T.self) { group in
            group.addTask {
                return try await operation()
            }
            
            group.addTask {
                try await Task.sleep(nanoseconds: UInt64(seconds * 1_000_000_000))
                throw TimeoutError()
            }
            
            guard let result = try await group.next() else {
                throw TimeoutError()
            }
            
            group.cancelAll()
            return result
        }
    }
    
    // MARK: - Order Management Methods
    
    @MainActor
    public func cancelOrder(orderId: String) async throws {
        guard let restaurantId = supabaseManager.currentRestaurantId else {
            throw OrderManagerError.missingRestaurantId
        }
        
        // Check if order exists and can be canceled
        let order: Order = try await supabaseManager.client
            .from("orders")
            .select("id, status")
            .eq("id", value: orderId)
            .eq("restaurant_id", value: restaurantId)
            .single()
            .execute()
            .value
        
        guard order.status == .new || order.status == .draft || order.status == .serving else {
            throw OrderManagerError.generalError(String(format: "error_cancel_order_status".localized, order.status.displayName))
        }
        
        // Update order status to canceled
        try await supabaseManager.client
            .from("orders")
            .update(["status": "canceled"])
            .eq("id", value: orderId)
            .execute()
        
        // Update all order items to canceled  
        try await supabaseManager.client
            .from("order_items")
            .update(["status": "canceled"])
            .eq("order_id", value: orderId)
            .execute()
        
        print("✅ canceled order: \(orderId)")
        
        // Refresh orders list
        await fetchActiveOrders()
    }

    // Add the new method here
    func countForFilter(_ filter: OrdersView.OrderFilter, allOrders: Bool) -> Int {
        let orders = allOrders ? self.allOrders : self.orders

        switch filter {
        case .active:
            return orders.filter { $0.status == .new || $0.status == .serving }.count
        case .new:
            return orders.filter { $0.status == .new }.count
        case .serving:
            return orders.filter { $0.status == .serving }.count
        case .completed:
            return orders.filter { $0.status == .completed }.count
        case .canceled:
            return orders.filter { $0.status == .canceled }.count
        }
    }
}

struct TimeoutError: LocalizedError {
    var errorDescription: String? {
        return "timeout_error".localized
    }
}
