import Foundation
import Supabase
import Combine
#if os(iOS)
import UIKit
#endif

// MARK: - Auto-printing Statistics
struct AutoPrintStats {
    var totalNewOrdersPrinted: Int = 0
    var totalReadyItemsPrinted: Int = 0
    var lastPrintTime: Date? = nil
    var printFailures: Int = 0
    
    mutating func recordNewOrderPrint() {
        totalNewOrdersPrinted += 1
        lastPrintTime = Date()
    }
    
    mutating func recordReadyItemPrint() {
        totalReadyItemsPrinted += 1
        lastPrintTime = Date()
    }
    
    mutating func recordPrintFailure() {
        printFailures += 1
    }
    
    mutating func reset() {
        totalNewOrdersPrinted = 0
        totalReadyItemsPrinted = 0
        lastPrintTime = nil
        printFailures = 0
    }
}

class OrderManager: ObservableObject {
    static let shared = OrderManager()
    
    private let supabaseManager = SupabaseManager.shared
    private let printerManager = PrinterManager.shared
    private let autoPrintQueue = DispatchQueue(label: "auto-print-queue", qos: .userInitiated)
    
    @Published var orders: [Order] = []
    @Published var allOrders: [Order] = []  // Add missing allOrders property
    @Published var isLoading = false
    @Published var errorMessage: String? = nil
    @Published var isRealtimeConnected = false
    @Published var newOrderIds: Set<String> = []
    
    // Auto-printing tracking
    @Published var autoPrintingEnabled = true
    @Published var lastAutoPrintResult: String? = nil
    @Published var autoPrintingInProgress = false
    @Published var autoPrintStats = AutoPrintStats()
    internal var printedNewOrders: Set<String> = []
    internal var printedReadyItems: Set<String> = []

    @Published var currentDraftOrder: Order? = nil // For managing the active draft order
    
    private var realtimeChannel: RealtimeChannelV2?
    private var cancellables = Set<AnyCancellable>()

    // Placeholder types for MenuItemSize and Topping, assuming they exist elsewhere
    // If not, these would be String or [String] for IDs
    typealias MenuItemSizeId = String // String ID for MenuItemSize
    typealias ToppingId = String      // String ID for Topping

    // Define status constants
    let ORDER_STATUS_DRAFT = "draft"
    let ORDER_ITEM_STATUS_DRAFT = "new" // Use 'new' status for items in draft orders (per DB constraint)
    let ORDER_STATUS_NEW = "new" // For when order is confirmed to kitchen

    enum OrderManagerError: Error, LocalizedError {
        case notImplemented
        case generalError(String)
        case missingRestaurantId
        case missingUserId
        case itemFetchFailed(String) // menuItemId
        case orderUpdateFailed(String) // orderId
        case orderItemUpdateFailed(String) // orderItemId

        var errorDescription: String? {
            switch self {
            case .notImplemented:
                return "This feature is not yet implemented."
            case .generalError(let message):
                return message
            case .missingRestaurantId:
                return "Restaurant ID is missing. Cannot perform operation."
            case .missingUserId:
                return "User ID is missing. Cannot create order."
            case .itemFetchFailed(let menuItemId):
                return "Failed to fetch details for menu item \(menuItemId)."
            case .orderUpdateFailed(let orderId):
                return "Failed to update order \(orderId)."
            case .orderItemUpdateFailed(let orderItemId):
                return "Failed to update order item \(orderItemId)."
            }
        }
    }

    // MARK: - Payload Structs for Supabase
    struct NewOrderPayload: Codable {
        let restaurant_id: String
        let table_id: String
        let user_id: String // Assuming user_id is the UUID of the authenticated user
        let guest_count: Int?
        var status: String
        var total_amount: Double = 0 // Initial total price
        // order_number can be generated by a database trigger or function
    }

    struct NewOrderItemPayload: Codable {
        let order_id: String
        let menu_item_id: String
        let quantity: Int
        let notes: String?
        let restaurant_id: String
        var price_at_order: Double // Price of the item at the time of order (including size/toppings)
        var status: String
        let menu_item_size_id: MenuItemSizeId?
        let topping_ids: [ToppingId]?
    }

    struct UpdateOrderItemPayload: Codable {
        let quantity: Int
        let notes: String?
        var updated_at: String = ISO8601DateFormatter().string(from: Date())
        // Potentially price_at_order if quantity/options change price
    }
    
    private init() {
        // Monitor authentication state changes
        setupAuthenticationMonitoring()
        loadAutoPrintingSettings()
    }
    
    deinit {
        //realtimeChannel?.unsubscribe()
        cancellables.removeAll()
    }

    // MARK: - New Order Creation & Management

    @MainActor
    public func startNewOrder(tableId: String, guestCount: Int?) async throws -> Order {
        guard let restaurantId = supabaseManager.currentRestaurantId else {
            throw OrderManagerError.missingRestaurantId
        }
        guard let userId = supabaseManager.currentUser?.id.uuidString else {
            // In a real app, user ID should always be available after login.
            // This might indicate an issue with session management or user data fetching.
            throw OrderManagerError.missingUserId
        }

        let newOrderPayload = NewOrderPayload(
            restaurant_id: restaurantId,
            table_id: tableId,
            user_id: userId, // Assuming current authenticated user is placing the order
            guest_count: guestCount,
            status: ORDER_STATUS_DRAFT
        )

        do {
            let createdOrder: Order = try await supabaseManager.client
                .from("orders")
                .insert(newOrderPayload, returning: .representation)
                .select("*, table:tables(*), order_items(*, menu_item:menu_items(*))") // Fetch related data
                .single()
                .execute()
                .value

            self.currentDraftOrder = createdOrder
            print("Draft order started: \(createdOrder.id)")
            return createdOrder
        } catch {
            print("Error starting new order: \(error)")
            throw OrderManagerError.generalError("Failed to start new order: \(error.localizedDescription)")
        }
    }

    @MainActor
    public func addItemToDraftOrder(orderId: String, menuItemId: String, quantity: Int, notes: String?, selectedSizeId: MenuItemSizeId?, selectedToppingIds: [ToppingId]?, priceAtOrder: Double) async throws -> OrderItem {

        guard let restaurantId = supabaseManager.currentRestaurantId else {
            throw OrderManagerError.missingRestaurantId
        }

        // Price calculation is now done in AddItemDetailView and passed as priceAtOrder.
        // The MOCK PRICE CALCULATION block has been removed.

        let newOrderItemPayload = NewOrderItemPayload(
            order_id: orderId,
            menu_item_id: menuItemId,
            quantity: quantity,
            notes: notes,
            restaurant_id: restaurantId,
            price_at_order: priceAtOrder, // Use the price calculated and passed by the view
            status: ORDER_ITEM_STATUS_DRAFT,
            menu_item_size_id: selectedSizeId,
            topping_ids: selectedToppingIds
        )

        do {
            let createdOrderItem: OrderItem = try await supabaseManager.client
                .from("order_items")
                .insert(newOrderItemPayload, returning: .representation)
                .select("*, menu_item:menu_items(*), menu_item_size:menu_item_sizes(*)") // Fetch related data
                .single()
                .execute()
                .value

            // Append to currentDraftOrder
            if currentDraftOrder?.id == orderId {
                currentDraftOrder?.order_items?.append(createdOrderItem)
                // Recalculate total price for the draft order
                recalculateCurrentDraftOrderTotal()
            } else {
                // If currentDraftOrder is not set or is different, fetch it to ensure consistency
                _ = try await getDraftOrder(orderId: orderId)
                currentDraftOrder?.order_items?.append(createdOrderItem)
                recalculateCurrentDraftOrderTotal()
            }

            print("Item added to draft order: \(createdOrderItem.id)")
            return createdOrderItem
        } catch {
            print("Error adding item to draft order: \(error)")
            throw OrderManagerError.generalError("Failed to add item: \(error.localizedDescription)")
        }
    }

    @MainActor
    private func recalculateCurrentDraftOrderTotal() {
        guard var draftOrder = currentDraftOrder, let items = draftOrder.order_items else { return }

        let total = items.reduce(0.0) { acc, item in
            acc + (item.price_at_order * Double(item.quantity))
        }
        draftOrder.total_amount = total
        currentDraftOrder = draftOrder

        // Optionally, update the order total in the database immediately for draft orders
        // This could be useful if another device needs to see the running total.
        // However, it might be better to do this only when confirming the order or explicitly saving a draft.
        // For now, we'll keep the total local until confirm/save.
    }


    @MainActor
    public func updateDraftOrderItem(orderItemId: String, newQuantity: Int, newNotes: String?) async throws -> OrderItem {
        // Note: This simplified version doesn't recalculate price_at_order if options change.
        // A full implementation would need to handle potential changes to selectedSize/selectedToppings
        // and refetch/recalculate price_at_order if they impact it.

        let updatePayload = UpdateOrderItemPayload(
            quantity: newQuantity,
            notes: newNotes
        )

        do {
            let updatedOrderItem: OrderItem = try await supabaseManager.client
                .from("order_items")
                .update(updatePayload)
                .eq("id", value: orderItemId)
                .select("*, menu_item:menu_items(*), menu_item_size:menu_item_sizes(*)")
                .single()
                .execute()
                .value

            // Update in currentDraftOrder
            if let index = currentDraftOrder?.order_items?.firstIndex(where: { $0.id == orderItemId }) {
                currentDraftOrder?.order_items?[index] = updatedOrderItem
                recalculateCurrentDraftOrderTotal()
            }
            print("Draft order item updated: \(updatedOrderItem.id)")
            return updatedOrderItem
        } catch {
            print("Error updating draft order item: \(error)")
            throw OrderManagerError.orderItemUpdateFailed(orderItemId)
        }
    }

    @MainActor
    public func removeDraftOrderItem(orderItemId: String) async throws {
        do {
            try await supabaseManager.client
                .from("order_items")
                .delete()
                .eq("id", value: orderItemId)
                .execute()

            // Remove from currentDraftOrder
            currentDraftOrder?.order_items?.removeAll(where: { $0.id == orderItemId })
            recalculateCurrentDraftOrderTotal()
            print("Draft order item removed: \(orderItemId)")
        } catch {
            print("Error removing draft order item: \(error)")
            throw OrderManagerError.generalError("Failed to remove item: \(error.localizedDescription)")
        }
    }

    @MainActor
    public func clearDraftOrder(orderId: String) async throws {
        // Ensure this order is the current draft before clearing locally
        if currentDraftOrder?.id != orderId {
             _ = try? await getDraftOrder(orderId: orderId) // Load it if not current
        }

        do {
            // 1. Delete all order_items associated with the orderId
            try await supabaseManager.client
                .from("order_items")
                .delete()
                .eq("order_id", value: orderId)
                .execute()
            print("Deleted items for draft order: \(orderId)")

            // 2. Delete the order itself
            try await supabaseManager.client
                .from("orders")
                .delete()
                .eq("id", value: orderId)
                .execute()
            print("Deleted draft order: \(orderId)")

            // Clear local state if it was the current draft
            if currentDraftOrder?.id == orderId {
                currentDraftOrder = nil
            }
        } catch {
            print("Error clearing draft order: \(error)")
            throw OrderManagerError.generalError("Failed to clear draft order: \(error.localizedDescription)")
        }
    }

    @MainActor
    public func confirmOrderToKitchen(orderId: String) async throws -> Order {
        var orderToConfirm: Order
        
        if let currentOrder = currentDraftOrder, currentOrder.id == orderId {
            orderToConfirm = currentOrder
        } else {
            // Fetch the order from database
            if let fetchedOrder = try await getDraftOrder(orderId: orderId, forceFetch: true) {
                orderToConfirm = fetchedOrder
            } else {
                throw OrderManagerError.orderUpdateFailed("Order \(orderId) not found for confirmation.")
            }
        }

        // Recalculate total price one last time based on current items, just in case.
        let finalTotalPrice = orderToConfirm.order_items?.reduce(0.0) { $0 + ($1.price_at_order * Double($1.quantity)) } ?? 0

        // Create a proper Codable struct for the update payload
        struct OrderUpdatePayload: Codable {
            let status: String
            let total_amount: Double
            let updated_at: String
        }
        
        let updatePayload = OrderUpdatePayload(
            status: "new", // Change status to "new" or similar for kitchen
            total_amount: finalTotalPrice,
            updated_at: ISO8601DateFormatter().string(from: Date())
        )

        do {
            let confirmedOrder: Order = try await supabaseManager.client
                .from("orders")
                .update(updatePayload)
                .eq("id", value: orderId)
                .select("*, table:tables(*), order_items(*, menu_item:menu_items(*), menu_item_size:menu_item_sizes(*))")
                .single()
                .execute()
                .value

            // Clear the local draft order state as it's no longer a draft
            currentDraftOrder = nil

            // Optionally, add to the main `orders` list if it's now an active order
            // Or rely on real-time updates / next fetchActiveOrders to pick it up.
            // For immediate UI update, consider adding it:
            if !self.orders.contains(where: { $0.id == confirmedOrder.id }) {
                 self.orders.insert(confirmedOrder, at: 0) // Add to top
            }

            print("Order confirmed to kitchen: \(confirmedOrder.id)")
            return confirmedOrder
        } catch {
            print("Error confirming order to kitchen: \(error)")
            throw OrderManagerError.orderUpdateFailed(orderId)
        }
    }

    @MainActor
    public func getDraftOrder(orderId: String, forceFetch: Bool = false) async throws -> Order? {
        if !forceFetch, let currentDraft = currentDraftOrder, currentDraft.id == orderId {
            // If we have a cached version and not forcing fetch, return it.
            // However, if its items are nil or empty, it might be an incompletely loaded order.
            // A more robust cache would check if items are also populated.
            // For now, this basic cache stands.
            print("Returning cached currentDraftOrder for id: \(orderId)")
            return currentDraft
        }
        // If orderId is "previewOrder123" or similar, it implies a preview context.
        // For robust previews that don't rely on DB state, construct a full mock Order here.
        if orderId.starts(with: "previewOrder") || orderId == "mockDraftOrder123" { // Adjusted for DraftOrderView preview
            print("getDraftOrder constructing MOCK for orderId: \(orderId)")
            // Create mock MenuItems for more realistic OrderItems in the preview
            let mockCat = Category(id: "cat_mock_drinks", name_en: "Mock Drinks", name_ja: nil, name_vi: nil, position: 1)
            let mockMenuItem1 = MenuItem(id: "menuItem1_mock_preview", restaurant_id: "resto_preview", category_id: mockCat.id, name_en: "Mock Coffee", name_ja: nil, name_vi: nil, code: "MC01", description_en: "A warm mock coffee", description_ja: nil, description_vi: nil, price: 3.00, tags: nil, image_url: nil, stock_level: nil, available: true, position: 1, created_at: Date().ISO8601Format(), updated_at: Date().ISO8601Format(), category: mockCat, availableSizes: nil, availableToppings: nil)
            let mockMenuItem2 = MenuItem(id: "menuItem2_mock_preview", restaurant_id: "resto_preview", category_id: mockCat.id, name_en: "Mock Tea", name_ja: nil, name_vi: nil, code: "MT01", description_en: "A soothing mock tea", description_ja: nil, description_vi: nil, price: 2.50, tags: nil, image_url: nil, stock_level: nil, available: true, position: 2, created_at: Date().ISO8601Format(), updated_at: Date().ISO8601Format(), category: mockCat, availableSizes: nil, availableToppings: nil)

            let mockItem1 = OrderItem(id: "mockPreviewItem1", restaurant_id: "resto_preview", order_id: orderId, menu_item_id: mockMenuItem1.id, quantity: 2, notes: "Extra hot", menu_item_size_id: nil, topping_ids: nil, price_at_order: 3.00, status: .draft, created_at: Date().ISO8601Format(), updated_at: Date().ISO8601Format(), menu_item: mockMenuItem1)
            let mockItem2 = OrderItem(id: "mockPreviewItem2", restaurant_id: "resto_preview", order_id: orderId, menu_item_id: mockMenuItem2.id, quantity: 1, notes: nil, menu_item_size_id: nil, topping_ids: nil, price_at_order: 2.50, status: .draft, created_at: Date().ISO8601Format(), updated_at: Date().ISO8601Format(), menu_item: mockMenuItem2)

            let mockTable = Table(
                id: "table_mock_preview_om", restaurant_id: "resto_preview", name: "Preview Tbl OM", status: .occupied,
                capacity: 2, is_outdoor: false, is_accessible: true, notes: nil, qr_code: nil,
                created_at: Date().ISO8601Format(), updated_at: Date().ISO8601Format()
            )

            let mockOrderInstance = Order(
                id: orderId, restaurant_id: "resto_preview", table_id: mockTable.id,
                session_id: "session_preview", guest_count: 2, status: .draft, total_amount: 8.50, // 2*3.00 + 2.50
                order_number: Int.random(in: 100...200), created_at: Date().ISO8601Format(), updated_at: Date().ISO8601Format(),
                table: mockTable, order_items: [mockItem1, mockItem2],
                payment_method: nil, discount_amount: nil, tax_amount: nil, tip_amount: nil
            )
            self.currentDraftOrder = mockOrderInstance
            return mockOrderInstance
        }
        print("Fetching draft order \(orderId) from database.")
        do {
            let orderResponse: Order = try await supabaseManager.client
                .from("orders")
                .select("*, table:tables(*), order_items(*, menu_item:menu_items(*, category:categories(*)), menu_item_size:menu_item_sizes(*))") // Added category to menu_item
                .eq("id", value: orderId)
                .eq("status", value: "draft") // Ensure it's still a draft
                .single() // Use single instead of maybeSingle
                .execute()
                .value

            self.currentDraftOrder = orderResponse
            return orderResponse
        } catch {
            print("Error fetching draft order \(orderId): \(error)")
            throw OrderManagerError.generalError("Failed to fetch draft order \(orderId): \(error.localizedDescription)")
        }
    }
    
    // MARK: - Auto-printing Settings
    
    private func loadAutoPrintingSettings() {
        autoPrintingEnabled = UserDefaults.standard.object(forKey: "auto_printing_enabled") as? Bool ?? true
    }
    
    func setAutoPrintingEnabled(_ enabled: Bool) {
        autoPrintingEnabled = enabled
        UserDefaults.standard.set(enabled, forKey: "auto_printing_enabled")
    }
    
    // MARK: - Authentication Monitoring
    private func setupAuthenticationMonitoring() {
        // Listen for authentication state changes
        supabaseManager.$isAuthenticated
            .combineLatest(supabaseManager.$currentRestaurant)
            .sink { [weak self] (isAuthenticated, restaurant) in
                // Use Task to bridge async context
                Task { @MainActor in
                    if isAuthenticated && restaurant != nil {
                        await self?.onAuthenticationSuccess()
                    } else {
                        await self?.onAuthenticationLost()
                    }
                }
            }
            .store(in: &cancellables)
    }
    
    @MainActor
    private func onAuthenticationSuccess() async {
        print("Authentication successful - setting up OrderManager")
        await setupRealtimeSubscription()
        await fetchActiveOrders()
    }
    
    @MainActor
    private func onAuthenticationLost() async {
        print("Authentication lost - cleaning up OrderManager")
        await cleanupRealtimeSubscription()
        orders = []
        errorMessage = "Authentication required"
        isRealtimeConnected = false
    }
    
    // MARK: - Fetch Orders
    @MainActor
    func fetchActiveOrders() async {
        guard supabaseManager.isAuthenticated else {
            errorMessage = "User not authenticated"
            print("Cannot fetch orders - user not authenticated")
            return
        }
        
        guard let restaurantId = supabaseManager.currentRestaurantId else {
            errorMessage = "No restaurant ID available"
            print("Cannot fetch orders - no restaurant ID")
            return
        }
        
        isLoading = true
        errorMessage = nil
        
        do {
            // Use the optimized RPC function instead of client-side joins
            let response: [OrderWithTableResponse] = try await supabaseManager.client
                .rpc("get_active_orders_with_details", params: ["p_restaurant_id": restaurantId])
                .execute()
                .value
            
            // Still need to fetch related data for order items, table, etc.
            // This will be done in a separate, more efficient query
            var ordersWithDetails: [OrderWithTableResponse] = []
            
            for order in response {
                let orderWithDetails: OrderWithTableResponse = try await supabaseManager.client
                    .from("orders")
                    .select("""
                        *,
                        table:tables(*),
                        order_items(
                            *,
                            menu_item:menu_items(
                                *,
                                category:categories(
                                    id,
                                    name_en,
                                    name_ja,
                                    name_vi
                                )
                            ),
                            menu_item_size:menu_item_sizes(*)
                        )
                    """)
                    .eq("id", value: order.id)
                    .single()
                    .execute()
                    .value
                
                ordersWithDetails.append(orderWithDetails)
            }
            
            self.orders = ordersWithDetails.map { $0.toOrder() }
            print("Fetched \(orders.count) active orders using RPC")
            
        } catch {
            errorMessage = "Failed to fetch orders: \(error.localizedDescription)"
            print("Error fetching orders: \(error)")
        }
        
        isLoading = false
    }
    
    // Add missing fetchAllOrders method
    @MainActor
    func fetchAllOrders() async {
        guard supabaseManager.isAuthenticated else {
            errorMessage = "User not authenticated"
            print("Cannot fetch all orders - user not authenticated")
            return
        }
        
        guard let restaurantId = supabaseManager.currentRestaurantId else {
            errorMessage = "No restaurant ID available"
            print("Cannot fetch all orders - no restaurant ID")
            return
        }
        
        isLoading = true
        errorMessage = nil
        
        do {
            let response: [OrderWithTableResponse] = try await supabaseManager.client
                .from("orders")
                .select("""
                    *,
                    table:tables(*),
                    order_items(
                        *,
                        menu_item:menu_items(
                            *,
                            category:categories(
                                id,
                                name_en,
                                name_ja,
                                name_vi
                            )
                        ),
                        menu_item_size:menu_item_sizes(*)
                    )
                """)
                .eq("restaurant_id", value: restaurantId)
                .order("created_at", ascending: false)
                .execute()
                .value
            
            self.allOrders = response.map { $0.toOrder() }
            print("Fetched \(allOrders.count) total orders")
            
        } catch {
            errorMessage = "Failed to fetch all orders: \(error.localizedDescription)"
            print("Error fetching all orders: \(error)")
        }
        
        isLoading = false
    }
    
    // MARK: - Update Order Status
    @MainActor
    func updateOrderStatus(orderId: String, newStatus: OrderStatus) async throws {
        do {
            // Use a simple update without expecting the full object back
            let _ = try await supabaseManager.client
                .from("orders")
                .update([
                    "status": newStatus.rawValue,
                    "updated_at": ISO8601DateFormatter().string(from: Date())
                ])
                .eq("id", value: orderId)
                .execute()
            
            // Update local state
            if let index = orders.firstIndex(where: { $0.id == orderId }) {
                orders[index].status = newStatus
                orders[index].updated_at = ISO8601DateFormatter().string(from: Date())
                
                // If order is completed, remove it from the list
                if newStatus == .completed {
                    orders.remove(at: index)
                }
            }
            
            // Also update in allOrders if needed
            if let allIndex = allOrders.firstIndex(where: { $0.id == orderId }) {
                allOrders[allIndex].status = newStatus
                allOrders[allIndex].updated_at = ISO8601DateFormatter().string(from: Date())
            }
            
            print("Updated order status to \(newStatus.rawValue)")
            
        } catch {
            print("Error updating order status: \(error)")
            throw error
        }
    }
    
    // MARK: - Update Order Item Notes
    @MainActor
    func updateOrderItemNotes(orderItemId: String, notes: String?) async {
        do {
            let _: OrderItem = try await supabaseManager.client
                .from("order_items")
                .update([
                    "notes": notes
                ])
                .eq("id", value: orderItemId)
                .single()
                .execute()
                .value
            
            // Update local state
            for (orderIndex, order) in orders.enumerated() {
                if let orderItems = order.order_items,
                   let itemIndex = orderItems.firstIndex(where: { $0.id == orderItemId }) {
                    orders[orderIndex].order_items?[itemIndex] = OrderItem(
                        id: orderItems[itemIndex].id,
                        restaurant_id: orderItems[itemIndex].restaurant_id,
                        order_id: orderItems[itemIndex].order_id,
                        menu_item_id: orderItems[itemIndex].menu_item_id,
                        quantity: orderItems[itemIndex].quantity,
                        notes: notes,
                        menu_item_size_id: orderItems[itemIndex].menu_item_size_id,
                        topping_ids: orderItems[itemIndex].topping_ids,
                        price_at_order: orderItems[itemIndex].price_at_order,
                        status: orderItems[itemIndex].status,
                        created_at: orderItems[itemIndex].created_at,
                        updated_at: orderItems[itemIndex].updated_at,
                        menu_item: orderItems[itemIndex].menu_item
                    )
                    break
                }
            }
            
            print("Updated order item notes")
            
        } catch {
            errorMessage = "Failed to update order item notes: \(error.localizedDescription)"
            print("Error updating order item notes: \(error)")
        }
    }
    
    // MARK: - Cancel Order Item
    @MainActor
    func cancelOrderItem(orderItemId: String) async {
        do {
            // Set status to cancelled
            let _: OrderItem = try await supabaseManager.client
                .from("order_items")
                .update([
                    "status": OrderItemStatus.cancelled.rawValue,
                    "updated_at": ISO8601DateFormatter().string(from: Date())
                ])
                .eq("id", value: orderItemId)
                .single()
                .execute()
                .value
            
            // Update local state
            for (orderIndex, order) in orders.enumerated() {
                if let orderItems = order.order_items,
                   let itemIndex = orderItems.firstIndex(where: { $0.id == orderItemId }) {
                    orders[orderIndex].order_items?[itemIndex] = OrderItem(
                        id: orderItems[itemIndex].id,
                        restaurant_id: orderItems[itemIndex].restaurant_id,
                        order_id: orderItems[itemIndex].order_id,
                        menu_item_id: orderItems[itemIndex].menu_item_id,
                        quantity: orderItems[itemIndex].quantity,
                        notes: orderItems[itemIndex].notes,
                        menu_item_size_id: orderItems[itemIndex].menu_item_size_id,
                        topping_ids: orderItems[itemIndex].topping_ids,
                        price_at_order: orderItems[itemIndex].price_at_order,
                        status: .cancelled,
                        created_at: orderItems[itemIndex].created_at,
                        updated_at: ISO8601DateFormatter().string(from: Date()),
                        menu_item: orderItems[itemIndex].menu_item
                    )
                    break
                }
            }
            
            print("Cancelled order item: \(orderItemId)")
            
        } catch {
            errorMessage = "Failed to cancel order item: \(error.localizedDescription)"
            print("Error cancelling order item: \(error)")
        }
    }

    // MARK: - Update Order Item Status
    @MainActor
    func updateOrderItemStatus(orderItemId: String, newStatus: OrderItemStatus) async {
        do {
            let _: OrderItem = try await supabaseManager.client
                .from("order_items")
                .update([
                    "status": newStatus.rawValue
                ])
                .eq("id", value: orderItemId)
                .single()
                .execute()
                .value
            
            // Update local state
            for (orderIndex, order) in orders.enumerated() {
                if let orderItems = order.order_items,
                   let itemIndex = orderItems.firstIndex(where: { $0.id == orderItemId }) {
                    orders[orderIndex].order_items?[itemIndex] = OrderItem(
                        id: orderItems[itemIndex].id,
                        restaurant_id: orderItems[itemIndex].restaurant_id,
                        order_id: orderItems[itemIndex].order_id,
                        menu_item_id: orderItems[itemIndex].menu_item_id,
                        quantity: orderItems[itemIndex].quantity,
                        notes: orderItems[itemIndex].notes,
                        menu_item_size_id: orderItems[itemIndex].menu_item_size_id,
                        topping_ids: orderItems[itemIndex].topping_ids,
                        price_at_order: orderItems[itemIndex].price_at_order,
                        status: newStatus,
                        created_at: orderItems[itemIndex].created_at,
                        updated_at: orderItems[itemIndex].updated_at,
                        menu_item: orderItems[itemIndex].menu_item
                    )
                    break
                }
            }
            
            print("Updated order item status to \(newStatus.rawValue)")
            
        } catch {
            errorMessage = "Failed to update order item status: \(error.localizedDescription)"
            print("Error updating order item status: \(error)")
        }
    }
    
    // MARK: - Realtime Subscription Management
    private func setupRealtimeSubscription() async {
        // Clean up any existing subscription first
        await cleanupRealtimeSubscription()
        
        guard supabaseManager.isAuthenticated else {
            print("Cannot setup realtime subscription - user not authenticated")
            return
        }
        
        guard let restaurantId = supabaseManager.currentRestaurantId else {
            print("Cannot setup realtime subscription - no restaurant ID")
            return
        }
        
        print("Setting up realtime subscription for restaurant: \(restaurantId)")
        
        realtimeChannel = supabaseManager.client.realtimeV2.channel("orders-\(restaurantId)")
        
        // Listen for order insertions
        if let ordersInsertion = realtimeChannel?.postgresChange(
            InsertAction.self,
            schema: "public",
            table: "orders",
            filter: "restaurant_id=eq.\(restaurantId)"
        ) {
            Task { [weak self] in
                for await _ in ordersInsertion {
                    print("New order inserted via realtime")
                    await MainActor.run {
                        Task { @MainActor in
                            await self?.handleOrderChange()
                        }
                    }
                }
            }
        }
        // Listen for order updates
        if let ordersUpdate = realtimeChannel?.postgresChange(
            UpdateAction.self,
            schema: "public",
            table: "orders",
            filter: "restaurant_id=eq.\(restaurantId)"
        ) {
            Task { [weak self] in
                for await _ in ordersUpdate {
                    print("Order updated via realtime")
                    await MainActor.run {
                        Task { @MainActor in
                            await self?.handleOrderChange()
                        }
                    }
                }
            }
        }
        // Listen for order item updates
        if let orderItemsUpdate = realtimeChannel?.postgresChange(
            UpdateAction.self,
            schema: "public",
            table: "order_items"
        ) {
            Task { [weak self] in
                for await _ in orderItemsUpdate {
                    print("Order item updated via realtime")
                    await MainActor.run {
                        Task { @MainActor in
                            await self?.handleOrderItemChange()
                        }
                    }
                }
            }
        }
        // Listen for subscription status
        if let channel = realtimeChannel {
            Task { [weak self] in
                await channel.subscribe()
                await MainActor.run {
                    self?.isRealtimeConnected = true
                }
            }
        }
    }
    
    private func cleanupRealtimeSubscription() async {
        if let channel = realtimeChannel {
            await channel.unsubscribe()
            realtimeChannel = nil
            print("Cleaned up realtime subscription")
        }
        await MainActor.run {
            isRealtimeConnected = false
        }
    }
    
    @MainActor
    private func handleOrderChange() async {
        let previousOrders = orders
        await fetchActiveOrders()
        
        // Check for new orders to auto-print
        if orders.count > previousOrders.count {
            triggerFeedback()
            
            // Auto-print new orders if enabled and kitchen printer is configured
            if autoPrintingEnabled && hasKitchenPrinter() {
                await autoPrintNewOrders(previousOrders: previousOrders)
            }
        }
    }
    
    @MainActor
    private func handleOrderItemChange() async {
        let previousOrders = orders
        
        // Refresh orders when order items change
        await fetchActiveOrders()
        
        // Check for items changing to "ready" status for auto-printing
        if autoPrintingEnabled && hasKitchenPrinter() {
            await autoPrintReadyItems(previousOrders: previousOrders)
        }
    }
    
    // MARK: - Public Methods for Manual Control
    @MainActor
    func refreshOrders() async {
        await fetchActiveOrders()
    }
    
    @MainActor
    func reconnectRealtime() async {
        await setupRealtimeSubscription()
    }

    private func triggerFeedback() {
        #if os(iOS)
        let generator = UINotificationFeedbackGenerator()
        generator.notificationOccurred(.success)
        #endif
    }
    
    // MARK: - Auto-printing Methods
    
    private func hasKitchenPrinter() -> Bool {
        let settingsManager = PrinterSettingsManager.shared
        return settingsManager.hasKitchenPrinter() || settingsManager.isUsingDefaultPrinter()
    }
    
    @MainActor
    private func autoPrintNewOrders(previousOrders: [Order]) async {
        await withCheckedContinuation { (continuation: CheckedContinuation<Void, Never>) in
            autoPrintQueue.async {
                Task {
                    await self.performAutoPrintNewOrders(previousOrders: previousOrders)
                    continuation.resume()
                }
            }
        }
    }
    
    private func performAutoPrintNewOrders(previousOrders: [Order]) async {
        let newOrders = findNewOrders(currentOrders: orders, previousOrders: previousOrders)
        
        guard !newOrders.isEmpty else { return }
        
        await MainActor.run {
            autoPrintingInProgress = true
        }
        
        for order in newOrders {
            // Skip if already printed
            if printedNewOrders.contains(order.id) {
                continue
            }
            
            // Only print if order has items
            guard let items = order.order_items, !items.isEmpty else {
                continue
            }
            
            do {
                // Use the shared PrinterManager instance instead of creating a new one
                try await printerManager.printKitchenSlip(for: order)
                printedNewOrders.insert(order.id)
                await MainActor.run {
                    autoPrintStats.recordNewOrderPrint()
                }
                
                let tableInfo = order.table?.name ?? "Table \(order.table_id)"
                await MainActor.run {
                    lastAutoPrintResult = "✅ Auto-printed new order for \(tableInfo)"
                }
                print("Auto-printed new order: \(order.id) for \(tableInfo)")
                
            } catch {
                await MainActor.run {
                    autoPrintStats.recordPrintFailure()
                    lastAutoPrintResult = "❌ Auto-print failed: \(error.localizedDescription)"
                }
                print("Auto-print failed for new order \(order.id): \(error.localizedDescription)")
            }
        }
        
        await MainActor.run {
            autoPrintingInProgress = false
        }
        
        // Clear the result message after 5 seconds
        Task {
            try? await Task.sleep(nanoseconds: 5_000_000_000)
            await MainActor.run {
                lastAutoPrintResult = nil
            }
        }
    }
    
    @MainActor
    private func autoPrintReadyItems(previousOrders: [Order]) async {
        let readyItems = findItemsChangedToReady(currentOrders: orders, previousOrders: previousOrders)
        
        guard !readyItems.isEmpty else { return }
        
        autoPrintingInProgress = true
        
        for item in readyItems {
            // Skip if already printed
            if printedReadyItems.contains(item.id) {
                continue
            }
            
            // Find the order containing this item
            guard let order = orders.first(where: { order in
                order.order_items?.contains(where: { $0.id == item.id }) == true
            }) else {
                continue
            }
            
            do {
                try await printItemOverview(item: item, order: order)
                printedReadyItems.insert(item.id)
                autoPrintStats.recordReadyItemPrint()
                
                let itemName = item.menu_item?.displayName ?? "Unknown Item"
                let tableInfo = order.table?.name ?? "Table \(order.table_id)"
                lastAutoPrintResult = "✅ Auto-printed ready: \(itemName) for \(tableInfo)"
                print("Auto-printed ready item: \(item.id) - \(itemName)")
                
            } catch {
                autoPrintStats.recordPrintFailure()
                lastAutoPrintResult = "❌ Auto-print failed: \(error.localizedDescription)"
                print("Auto-print failed for ready item \(item.id): \(error.localizedDescription)")
            }
        }
        
        autoPrintingInProgress = false
        
        // Clear the result message after 5 seconds
        Task {
            try? await Task.sleep(nanoseconds: 5_000_000_000)
            lastAutoPrintResult = nil
        }
    }
    
    internal func findNewOrders(currentOrders: [Order], previousOrders: [Order]) -> [Order] {
        let previousOrderIds = Set(previousOrders.map { $0.id })
        return currentOrders.filter { !previousOrderIds.contains($0.id) }
    }
    
    internal func findItemsChangedToReady(currentOrders: [Order], previousOrders: [Order]) -> [OrderItem] {
        var readyItems: [OrderItem] = []
        
        // Create lookup for previous order items
        var previousItemStatuses: [String: OrderItemStatus] = [:]
        for order in previousOrders {
            if let items = order.order_items {
                for item in items {
                    previousItemStatuses[item.id] = item.status
                }
            }
        }
        
        // Check current orders for items that changed to ready
        for order in currentOrders {
            if let items = order.order_items {
                for item in items {
                    if item.status == .ready {
                        let previousStatus = previousItemStatuses[item.id]
                        if previousStatus != .ready {
                            readyItems.append(item)
                        }
                    }
                }
            }
        }
        
        return readyItems
    }
    
    @MainActor
    private func printItemOverview(item: OrderItem, order: Order) async throws {
        let settingsManager = PrinterSettingsManager.shared
        let printerService = PrinterService.shared
        
        // Create a simple overview format for ready items
        var overview = "ITEM READY\n"
        overview += String(repeating: "=", count: 32) + "\n"
        overview += "Item: \(item.menu_item?.displayName ?? "Unknown Item")\n"
        overview += "Table: \(order.table?.name ?? "Table \(order.table_id)")\n"
        overview += "Quantity: \(item.quantity)\n"
        
        if let notes = item.notes, !notes.isEmpty {
            overview += "Notes: \(notes)\n"
        }
        
        overview += "Time: \(DateFormatter.localizedString(from: Date(), dateStyle: .none, timeStyle: .short))\n"
        overview += String(repeating: "=", count: 32) + "\n\n\n"
        
        let printData = Data(overview.utf8)
        
        // Use kitchen printer if configured, otherwise use default
        switch settingsManager.printerMode {
        case .single:
            try await printerService.connectAndSendData(data: printData)
        case .dual:
            if let kitchenConfig = settingsManager.getKitchenPrinterConfig() {
                try await printerService.connectAndSendData(data: printData, to: kitchenConfig)
            } else {
                try await printerService.connectAndSendData(data: printData)
            }
        }
    }
    
    // MARK: - Clear Print History (for testing/reset)
    
    func clearPrintHistory() {
        printedNewOrders.removeAll()
        printedReadyItems.removeAll()
        autoPrintStats.reset()
        lastAutoPrintResult = "🔄 Print history cleared"
        print("Print history and statistics cleared")
        
        // Clear the result message after 3 seconds
        Task {
            try? await Task.sleep(nanoseconds: 3_000_000_000)
            lastAutoPrintResult = nil
        }
    }
    
    // MARK: - Helper Functions
    // Ensure TimeoutError is defined if not already present, or use a general error.
    // struct TimeoutError: LocalizedError { ... } was present at the end of the original file.
    private func withTimeout<T>(seconds: TimeInterval, operation: @escaping () async throws -> T) async throws -> T {
        return try await withThrowingTaskGroup(of: T.self) { group in
            group.addTask {
                return try await operation()
            }
            
            group.addTask {
                try await Task.sleep(nanoseconds: UInt64(seconds * 1_000_000_000))
                throw TimeoutError()
            }
            
            guard let result = try await group.next() else {
                throw TimeoutError()
            }
            
            group.cancelAll()
            return result
        }
    }
}

struct TimeoutError: LocalizedError {
    var errorDescription: String? {
        return "Request timed out"
    }
}
